apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: kodesmil-issuer
  namespace: cert-manager
spec:
  acme:
    email: hello@kodesmil.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: kodesmil-issuer-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token