apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: go-patient-registry
build:
  artifacts:
    - image: go-patient-registry
deploy:
  helm:
    releases:
      - name: go-patient-registry
        chartPath: go-patient-registry
        namespace: qa
        version: 1.0.0
        values:
          image.repository: go-patient-registry
portForward:
- resourceType: deployment
  resourceName: go-patient-registry
  port: 5432
  localPort: 5432
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
