apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: ks-backend
build:
  artifacts:
    - image: docker.io/kodesmil/ks-backend
      docker:
        dockerfile: deployments/Dockerfile
deploy:
  helm:
    releases:
      - name: postgresql
        chartPath: bitnami/postgresql
        wait: true
        remote: true
        overrides:
          postgresqlDatabase: swanly
          postgresqlPassword: postgres
      - name: ion
        chartPath: ion/kube/ion
        wait: true
        skipBuildDependencies: true
        valuesFiles:
          - deployments/ion/values.yaml
  kubectl:
    manifests:
      - deployments/deployment.yaml
      - deployments/ingress.yaml
      - deployments/secret.yaml
      - deployments/service.yaml