apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: ks-backend
build:
  artifacts:
    - image: docker.io/kodesmil/ks-backend
      docker:
        dockerfile: Dockerfile
        cacheFrom:
          - docker.io/kodesmil/ks-backend:latest
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: postgresql
        chartPath: bitnami/postgresql
        wait: true
        remote: true
        overrides:
          postgresqlDatabase: swanly
          postgresqlPassword: postgres
  kubectl:
    manifests:
      - manifests/ingress.yaml
      - manifests/deployment.yaml
      - manifests/secret.yaml
      - manifests/service.yaml