apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: ks-backend
build:
    # useBuildkit: true
  local:
  artifacts:
  - image: docker.io/kodesmil/ks-backend
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
    - manifests/ingress.yaml
    - manifests/secret.yaml
    - manifests/service.yaml
