apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: ks-backend
build:
  tagPolicy:
    sha256: {}
  # local:
  # useBuildkit: true
  artifacts:
  - image: docker.io/kodesmil/ks-backend
    docker:
      dockerfile: Dockerfile
      cacheFrom:
        - docker.io/kodesmil/ks-backend:latest
deploy:
  helm:
    releases:
      - name: postgresql
        chartPath: bitnami/postgresql
        remote: true
        wait: true
        overrides:
          postgresqlPassword: postgres
          postgresqlDatabase: swanly
  kubectl:
    manifests:
    - manifests/ingress.yaml
    - manifests/deployment.yaml
    - manifests/secret.yaml
    - manifests/service.yaml