apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: ks-backend
build:
  artifacts:
    - image: docker.io/kodesmil/ks-backend
      docker:
        dockerfile: deployments/Dockerfile
    - image: docker.io/kodesmil/ion-avp
      context: ion
      docker:
        dockerfile: docker/avp.Dockerfile
    - image: docker.io/kodesmil/ion-biz
      context: ion
      docker:
        dockerfile: docker/biz.Dockerfile
    - image: docker.io/kodesmil/ion-sfu
      context: ion
      docker:
        dockerfile: docker/sfu.Dockerfile
    - image: docker.io/kodesmil/ion-islb
      context: ion
      docker:
        dockerfile: docker/islb.Dockerfile
deploy:
  helm:
    releases:
      - name: postgresql
        chartPath: bitnami/postgresql
        wait: true
        remote: true
        overrides:
          postgresqlDatabase: swanly
          postgresqlPassword: postgres
      - name: ion-nats
        chartPath: bitnami/nats
        wait: true
        remote: true
        setValues:
          auth.enabled: "false"
          metrics.enabled: "true"
      - name: ion-redis
        chartPath: bitnami/redis
        wait: true
        remote: true
        overrides:
          usePassword: false
          metrics.enabled: true
      - name: ion-etcd
        chartPath: bitnami/etcd
        wait: true
        remote: true
        setValues:
          auth.rbac.enabled: "false"
          metrics.enabled: "true"
  kubectl:
    manifests:
      - deployments/deployment.yaml
      - deployments/ingress.yaml
      - deployments/secret.yaml
      - deployments/service.yaml
      - ion/kube/biz.yaml
      - ion/kube/config.yaml
      - ion/kube/ingress.yaml
      - ion/kube/islb.yaml
      - ion/kube/sfu.yaml
      - ion/kube/web.yaml