apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: go-patient-registry
build:
  local:
    # useBuildkit: true
  artifacts:
  - image: gcr.io/motim1/go-patient-registry
deploy:
  kubectl:
    manifests:
    - manifests/deployment.yaml
    - manifests/ingress.yaml
    - manifests/secret.yaml
    - manifests/service.yaml
