apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: go-patient-registry
build:
  artifacts:
    - image: kodesmil/go-patient-registry
deploy:
  helm:
    releases:
      - name: go-patient-registry-helm
        chartPath: go-patient-registry-helm
        namespace: dev
        version: 1.0.0
        values:
          image.repository: kodesmil/go-patient-registry
