apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-patient-registry.fullname" . }}
  labels:
    {{- include "go-patient-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "go-patient-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-patient-registry.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.service.debugPort }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/secrets/firebase-service-config.json"
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.healthPort }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.healthPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: secrets
          secret:
            secretName: kodesmil-secret-files
