apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-patient-registry-helm.fullname" . }}
  labels:
    {{- include "go-patient-registry-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "go-patient-registry-helm.selectorLabels" . | nindent 4 }}
