// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kodesmil/ks-model/health.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthMenstruationDailyEntry_Type int32

const (
	HealthMenstruationDailyEntry_PERIOD    HealthMenstruationDailyEntry_Type = 0
	HealthMenstruationDailyEntry_OVULATION HealthMenstruationDailyEntry_Type = 1
)

var HealthMenstruationDailyEntry_Type_name = map[int32]string{
	0: "PERIOD",
	1: "OVULATION",
}

var HealthMenstruationDailyEntry_Type_value = map[string]int32{
	"PERIOD":    0,
	"OVULATION": 1,
}

func (x HealthMenstruationDailyEntry_Type) String() string {
	return proto.EnumName(HealthMenstruationDailyEntry_Type_name, int32(x))
}

func (HealthMenstruationDailyEntry_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{1, 0}
}

type HealthMenstruationPersonalInfo struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PeriodLengthInDays   int32                `protobuf:"varint,4,opt,name=period_length_in_days,json=periodLengthInDays,proto3" json:"period_length_in_days,omitempty"`
	CycleLengthInDays    int32                `protobuf:"varint,5,opt,name=cycle_length_in_days,json=cycleLengthInDays,proto3" json:"cycle_length_in_days,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HealthMenstruationPersonalInfo) Reset()         { *m = HealthMenstruationPersonalInfo{} }
func (m *HealthMenstruationPersonalInfo) String() string { return proto.CompactTextString(m) }
func (*HealthMenstruationPersonalInfo) ProtoMessage()    {}
func (*HealthMenstruationPersonalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{0}
}

func (m *HealthMenstruationPersonalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthMenstruationPersonalInfo.Unmarshal(m, b)
}
func (m *HealthMenstruationPersonalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthMenstruationPersonalInfo.Marshal(b, m, deterministic)
}
func (m *HealthMenstruationPersonalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthMenstruationPersonalInfo.Merge(m, src)
}
func (m *HealthMenstruationPersonalInfo) XXX_Size() int {
	return xxx_messageInfo_HealthMenstruationPersonalInfo.Size(m)
}
func (m *HealthMenstruationPersonalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthMenstruationPersonalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HealthMenstruationPersonalInfo proto.InternalMessageInfo

func (m *HealthMenstruationPersonalInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HealthMenstruationPersonalInfo) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *HealthMenstruationPersonalInfo) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *HealthMenstruationPersonalInfo) GetPeriodLengthInDays() int32 {
	if m != nil {
		return m.PeriodLengthInDays
	}
	return 0
}

func (m *HealthMenstruationPersonalInfo) GetCycleLengthInDays() int32 {
	if m != nil {
		return m.CycleLengthInDays
	}
	return 0
}

type HealthMenstruationDailyEntry struct {
	Id                   uint64                            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp              `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp              `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Day                  *timestamp.Timestamp              `protobuf:"bytes,4,opt,name=day,proto3" json:"day,omitempty"`
	IntensityPercentage  int32                             `protobuf:"varint,5,opt,name=intensity_percentage,json=intensityPercentage,proto3" json:"intensity_percentage,omitempty"`
	Type                 HealthMenstruationDailyEntry_Type `protobuf:"varint,6,opt,name=type,proto3,enum=model.HealthMenstruationDailyEntry_Type" json:"type,omitempty"`
	Manual               bool                              `protobuf:"varint,7,opt,name=manual,proto3" json:"manual,omitempty"`
	BasedOnPrediction    bool                              `protobuf:"varint,8,opt,name=based_on_prediction,json=basedOnPrediction,proto3" json:"based_on_prediction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthMenstruationDailyEntry) Reset()         { *m = HealthMenstruationDailyEntry{} }
func (m *HealthMenstruationDailyEntry) String() string { return proto.CompactTextString(m) }
func (*HealthMenstruationDailyEntry) ProtoMessage()    {}
func (*HealthMenstruationDailyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{1}
}

func (m *HealthMenstruationDailyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthMenstruationDailyEntry.Unmarshal(m, b)
}
func (m *HealthMenstruationDailyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthMenstruationDailyEntry.Marshal(b, m, deterministic)
}
func (m *HealthMenstruationDailyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthMenstruationDailyEntry.Merge(m, src)
}
func (m *HealthMenstruationDailyEntry) XXX_Size() int {
	return xxx_messageInfo_HealthMenstruationDailyEntry.Size(m)
}
func (m *HealthMenstruationDailyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthMenstruationDailyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_HealthMenstruationDailyEntry proto.InternalMessageInfo

func (m *HealthMenstruationDailyEntry) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HealthMenstruationDailyEntry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *HealthMenstruationDailyEntry) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *HealthMenstruationDailyEntry) GetDay() *timestamp.Timestamp {
	if m != nil {
		return m.Day
	}
	return nil
}

func (m *HealthMenstruationDailyEntry) GetIntensityPercentage() int32 {
	if m != nil {
		return m.IntensityPercentage
	}
	return 0
}

func (m *HealthMenstruationDailyEntry) GetType() HealthMenstruationDailyEntry_Type {
	if m != nil {
		return m.Type
	}
	return HealthMenstruationDailyEntry_PERIOD
}

func (m *HealthMenstruationDailyEntry) GetManual() bool {
	if m != nil {
		return m.Manual
	}
	return false
}

func (m *HealthMenstruationDailyEntry) GetBasedOnPrediction() bool {
	if m != nil {
		return m.BasedOnPrediction
	}
	return false
}

type CreateHealthMenstruationDailyEntryRequest struct {
	Payload              *HealthMenstruationDailyEntry `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateHealthMenstruationDailyEntryRequest) Reset() {
	*m = CreateHealthMenstruationDailyEntryRequest{}
}
func (m *CreateHealthMenstruationDailyEntryRequest) String() string {
	return proto.CompactTextString(m)
}
func (*CreateHealthMenstruationDailyEntryRequest) ProtoMessage() {}
func (*CreateHealthMenstruationDailyEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{2}
}

func (m *CreateHealthMenstruationDailyEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest.Unmarshal(m, b)
}
func (m *CreateHealthMenstruationDailyEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest.Marshal(b, m, deterministic)
}
func (m *CreateHealthMenstruationDailyEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest.Merge(m, src)
}
func (m *CreateHealthMenstruationDailyEntryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest.Size(m)
}
func (m *CreateHealthMenstruationDailyEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHealthMenstruationDailyEntryRequest proto.InternalMessageInfo

func (m *CreateHealthMenstruationDailyEntryRequest) GetPayload() *HealthMenstruationDailyEntry {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateHealthMenstruationDailyEntryResponse struct {
	Result               *HealthMenstruationDailyEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateHealthMenstruationDailyEntryResponse) Reset() {
	*m = CreateHealthMenstruationDailyEntryResponse{}
}
func (m *CreateHealthMenstruationDailyEntryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CreateHealthMenstruationDailyEntryResponse) ProtoMessage() {}
func (*CreateHealthMenstruationDailyEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{3}
}

func (m *CreateHealthMenstruationDailyEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse.Unmarshal(m, b)
}
func (m *CreateHealthMenstruationDailyEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse.Marshal(b, m, deterministic)
}
func (m *CreateHealthMenstruationDailyEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse.Merge(m, src)
}
func (m *CreateHealthMenstruationDailyEntryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse.Size(m)
}
func (m *CreateHealthMenstruationDailyEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHealthMenstruationDailyEntryResponse proto.InternalMessageInfo

func (m *CreateHealthMenstruationDailyEntryResponse) GetResult() *HealthMenstruationDailyEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadHealthMenstruationDailyEntryRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadHealthMenstruationDailyEntryRequest) Reset() {
	*m = ReadHealthMenstruationDailyEntryRequest{}
}
func (m *ReadHealthMenstruationDailyEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ReadHealthMenstruationDailyEntryRequest) ProtoMessage()    {}
func (*ReadHealthMenstruationDailyEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{4}
}

func (m *ReadHealthMenstruationDailyEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest.Unmarshal(m, b)
}
func (m *ReadHealthMenstruationDailyEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest.Marshal(b, m, deterministic)
}
func (m *ReadHealthMenstruationDailyEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest.Merge(m, src)
}
func (m *ReadHealthMenstruationDailyEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest.Size(m)
}
func (m *ReadHealthMenstruationDailyEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadHealthMenstruationDailyEntryRequest proto.InternalMessageInfo

func (m *ReadHealthMenstruationDailyEntryRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadHealthMenstruationDailyEntryResponse struct {
	Result               *HealthMenstruationDailyEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ReadHealthMenstruationDailyEntryResponse) Reset() {
	*m = ReadHealthMenstruationDailyEntryResponse{}
}
func (m *ReadHealthMenstruationDailyEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ReadHealthMenstruationDailyEntryResponse) ProtoMessage()    {}
func (*ReadHealthMenstruationDailyEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{5}
}

func (m *ReadHealthMenstruationDailyEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse.Unmarshal(m, b)
}
func (m *ReadHealthMenstruationDailyEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse.Marshal(b, m, deterministic)
}
func (m *ReadHealthMenstruationDailyEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse.Merge(m, src)
}
func (m *ReadHealthMenstruationDailyEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse.Size(m)
}
func (m *ReadHealthMenstruationDailyEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadHealthMenstruationDailyEntryResponse proto.InternalMessageInfo

func (m *ReadHealthMenstruationDailyEntryResponse) GetResult() *HealthMenstruationDailyEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateHealthMenstruationDailyEntryRequest struct {
	Payload              *HealthMenstruationDailyEntry `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateHealthMenstruationDailyEntryRequest) Reset() {
	*m = UpdateHealthMenstruationDailyEntryRequest{}
}
func (m *UpdateHealthMenstruationDailyEntryRequest) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateHealthMenstruationDailyEntryRequest) ProtoMessage() {}
func (*UpdateHealthMenstruationDailyEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{6}
}

func (m *UpdateHealthMenstruationDailyEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest.Unmarshal(m, b)
}
func (m *UpdateHealthMenstruationDailyEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHealthMenstruationDailyEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest.Merge(m, src)
}
func (m *UpdateHealthMenstruationDailyEntryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest.Size(m)
}
func (m *UpdateHealthMenstruationDailyEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHealthMenstruationDailyEntryRequest proto.InternalMessageInfo

func (m *UpdateHealthMenstruationDailyEntryRequest) GetPayload() *HealthMenstruationDailyEntry {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateHealthMenstruationDailyEntryResponse struct {
	Result               *HealthMenstruationDailyEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *UpdateHealthMenstruationDailyEntryResponse) Reset() {
	*m = UpdateHealthMenstruationDailyEntryResponse{}
}
func (m *UpdateHealthMenstruationDailyEntryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateHealthMenstruationDailyEntryResponse) ProtoMessage() {}
func (*UpdateHealthMenstruationDailyEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{7}
}

func (m *UpdateHealthMenstruationDailyEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse.Unmarshal(m, b)
}
func (m *UpdateHealthMenstruationDailyEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHealthMenstruationDailyEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse.Merge(m, src)
}
func (m *UpdateHealthMenstruationDailyEntryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse.Size(m)
}
func (m *UpdateHealthMenstruationDailyEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHealthMenstruationDailyEntryResponse proto.InternalMessageInfo

func (m *UpdateHealthMenstruationDailyEntryResponse) GetResult() *HealthMenstruationDailyEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteHealthMenstruationDailyEntryRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHealthMenstruationDailyEntryRequest) Reset() {
	*m = DeleteHealthMenstruationDailyEntryRequest{}
}
func (m *DeleteHealthMenstruationDailyEntryRequest) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteHealthMenstruationDailyEntryRequest) ProtoMessage() {}
func (*DeleteHealthMenstruationDailyEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{8}
}

func (m *DeleteHealthMenstruationDailyEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest.Unmarshal(m, b)
}
func (m *DeleteHealthMenstruationDailyEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHealthMenstruationDailyEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest.Merge(m, src)
}
func (m *DeleteHealthMenstruationDailyEntryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest.Size(m)
}
func (m *DeleteHealthMenstruationDailyEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHealthMenstruationDailyEntryRequest proto.InternalMessageInfo

func (m *DeleteHealthMenstruationDailyEntryRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteHealthMenstruationDailyEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHealthMenstruationDailyEntryResponse) Reset() {
	*m = DeleteHealthMenstruationDailyEntryResponse{}
}
func (m *DeleteHealthMenstruationDailyEntryResponse) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteHealthMenstruationDailyEntryResponse) ProtoMessage() {}
func (*DeleteHealthMenstruationDailyEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{9}
}

func (m *DeleteHealthMenstruationDailyEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse.Unmarshal(m, b)
}
func (m *DeleteHealthMenstruationDailyEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHealthMenstruationDailyEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse.Merge(m, src)
}
func (m *DeleteHealthMenstruationDailyEntryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse.Size(m)
}
func (m *DeleteHealthMenstruationDailyEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHealthMenstruationDailyEntryResponse proto.InternalMessageInfo

type ListHealthMenstruationDailyEntryRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListHealthMenstruationDailyEntryRequest) Reset() {
	*m = ListHealthMenstruationDailyEntryRequest{}
}
func (m *ListHealthMenstruationDailyEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ListHealthMenstruationDailyEntryRequest) ProtoMessage()    {}
func (*ListHealthMenstruationDailyEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{10}
}

func (m *ListHealthMenstruationDailyEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryRequest.Unmarshal(m, b)
}
func (m *ListHealthMenstruationDailyEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryRequest.Marshal(b, m, deterministic)
}
func (m *ListHealthMenstruationDailyEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHealthMenstruationDailyEntryRequest.Merge(m, src)
}
func (m *ListHealthMenstruationDailyEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryRequest.Size(m)
}
func (m *ListHealthMenstruationDailyEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHealthMenstruationDailyEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHealthMenstruationDailyEntryRequest proto.InternalMessageInfo

func (m *ListHealthMenstruationDailyEntryRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListHealthMenstruationDailyEntryRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListHealthMenstruationDailyEntryRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListHealthMenstruationDailyEntryRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListHealthMenstruationDailyEntryResponse struct {
	Results              []*HealthMenstruationDailyEntry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ListHealthMenstruationDailyEntryResponse) Reset() {
	*m = ListHealthMenstruationDailyEntryResponse{}
}
func (m *ListHealthMenstruationDailyEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ListHealthMenstruationDailyEntryResponse) ProtoMessage()    {}
func (*ListHealthMenstruationDailyEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{11}
}

func (m *ListHealthMenstruationDailyEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryResponse.Unmarshal(m, b)
}
func (m *ListHealthMenstruationDailyEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryResponse.Marshal(b, m, deterministic)
}
func (m *ListHealthMenstruationDailyEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHealthMenstruationDailyEntryResponse.Merge(m, src)
}
func (m *ListHealthMenstruationDailyEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ListHealthMenstruationDailyEntryResponse.Size(m)
}
func (m *ListHealthMenstruationDailyEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHealthMenstruationDailyEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHealthMenstruationDailyEntryResponse proto.InternalMessageInfo

func (m *ListHealthMenstruationDailyEntryResponse) GetResults() []*HealthMenstruationDailyEntry {
	if m != nil {
		return m.Results
	}
	return nil
}

type CreateHealthMenstruationPersonalInfoRequest struct {
	Payload              *HealthMenstruationPersonalInfo `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CreateHealthMenstruationPersonalInfoRequest) Reset() {
	*m = CreateHealthMenstruationPersonalInfoRequest{}
}
func (m *CreateHealthMenstruationPersonalInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*CreateHealthMenstruationPersonalInfoRequest) ProtoMessage() {}
func (*CreateHealthMenstruationPersonalInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{12}
}

func (m *CreateHealthMenstruationPersonalInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest.Unmarshal(m, b)
}
func (m *CreateHealthMenstruationPersonalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateHealthMenstruationPersonalInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest.Merge(m, src)
}
func (m *CreateHealthMenstruationPersonalInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest.Size(m)
}
func (m *CreateHealthMenstruationPersonalInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHealthMenstruationPersonalInfoRequest proto.InternalMessageInfo

func (m *CreateHealthMenstruationPersonalInfoRequest) GetPayload() *HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateHealthMenstruationPersonalInfoResponse struct {
	Result               *HealthMenstruationPersonalInfo `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *CreateHealthMenstruationPersonalInfoResponse) Reset() {
	*m = CreateHealthMenstruationPersonalInfoResponse{}
}
func (m *CreateHealthMenstruationPersonalInfoResponse) String() string {
	return proto.CompactTextString(m)
}
func (*CreateHealthMenstruationPersonalInfoResponse) ProtoMessage() {}
func (*CreateHealthMenstruationPersonalInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{13}
}

func (m *CreateHealthMenstruationPersonalInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse.Unmarshal(m, b)
}
func (m *CreateHealthMenstruationPersonalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse.Marshal(b, m, deterministic)
}
func (m *CreateHealthMenstruationPersonalInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse.Merge(m, src)
}
func (m *CreateHealthMenstruationPersonalInfoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse.Size(m)
}
func (m *CreateHealthMenstruationPersonalInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHealthMenstruationPersonalInfoResponse proto.InternalMessageInfo

func (m *CreateHealthMenstruationPersonalInfoResponse) GetResult() *HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadHealthMenstruationPersonalInfoRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadHealthMenstruationPersonalInfoRequest) Reset() {
	*m = ReadHealthMenstruationPersonalInfoRequest{}
}
func (m *ReadHealthMenstruationPersonalInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ReadHealthMenstruationPersonalInfoRequest) ProtoMessage() {}
func (*ReadHealthMenstruationPersonalInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{14}
}

func (m *ReadHealthMenstruationPersonalInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest.Unmarshal(m, b)
}
func (m *ReadHealthMenstruationPersonalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest.Marshal(b, m, deterministic)
}
func (m *ReadHealthMenstruationPersonalInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest.Merge(m, src)
}
func (m *ReadHealthMenstruationPersonalInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest.Size(m)
}
func (m *ReadHealthMenstruationPersonalInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadHealthMenstruationPersonalInfoRequest proto.InternalMessageInfo

func (m *ReadHealthMenstruationPersonalInfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadHealthMenstruationPersonalInfoResponse struct {
	Result               *HealthMenstruationPersonalInfo `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ReadHealthMenstruationPersonalInfoResponse) Reset() {
	*m = ReadHealthMenstruationPersonalInfoResponse{}
}
func (m *ReadHealthMenstruationPersonalInfoResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ReadHealthMenstruationPersonalInfoResponse) ProtoMessage() {}
func (*ReadHealthMenstruationPersonalInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{15}
}

func (m *ReadHealthMenstruationPersonalInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse.Unmarshal(m, b)
}
func (m *ReadHealthMenstruationPersonalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse.Marshal(b, m, deterministic)
}
func (m *ReadHealthMenstruationPersonalInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse.Merge(m, src)
}
func (m *ReadHealthMenstruationPersonalInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse.Size(m)
}
func (m *ReadHealthMenstruationPersonalInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadHealthMenstruationPersonalInfoResponse proto.InternalMessageInfo

func (m *ReadHealthMenstruationPersonalInfoResponse) GetResult() *HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateHealthMenstruationPersonalInfoRequest struct {
	Payload              *HealthMenstruationPersonalInfo `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateHealthMenstruationPersonalInfoRequest) Reset() {
	*m = UpdateHealthMenstruationPersonalInfoRequest{}
}
func (m *UpdateHealthMenstruationPersonalInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateHealthMenstruationPersonalInfoRequest) ProtoMessage() {}
func (*UpdateHealthMenstruationPersonalInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{16}
}

func (m *UpdateHealthMenstruationPersonalInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest.Unmarshal(m, b)
}
func (m *UpdateHealthMenstruationPersonalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHealthMenstruationPersonalInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest.Merge(m, src)
}
func (m *UpdateHealthMenstruationPersonalInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest.Size(m)
}
func (m *UpdateHealthMenstruationPersonalInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHealthMenstruationPersonalInfoRequest proto.InternalMessageInfo

func (m *UpdateHealthMenstruationPersonalInfoRequest) GetPayload() *HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateHealthMenstruationPersonalInfoResponse struct {
	Result               *HealthMenstruationPersonalInfo `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateHealthMenstruationPersonalInfoResponse) Reset() {
	*m = UpdateHealthMenstruationPersonalInfoResponse{}
}
func (m *UpdateHealthMenstruationPersonalInfoResponse) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateHealthMenstruationPersonalInfoResponse) ProtoMessage() {}
func (*UpdateHealthMenstruationPersonalInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{17}
}

func (m *UpdateHealthMenstruationPersonalInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse.Unmarshal(m, b)
}
func (m *UpdateHealthMenstruationPersonalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHealthMenstruationPersonalInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse.Merge(m, src)
}
func (m *UpdateHealthMenstruationPersonalInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse.Size(m)
}
func (m *UpdateHealthMenstruationPersonalInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHealthMenstruationPersonalInfoResponse proto.InternalMessageInfo

func (m *UpdateHealthMenstruationPersonalInfoResponse) GetResult() *HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteHealthMenstruationPersonalInfoRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHealthMenstruationPersonalInfoRequest) Reset() {
	*m = DeleteHealthMenstruationPersonalInfoRequest{}
}
func (m *DeleteHealthMenstruationPersonalInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteHealthMenstruationPersonalInfoRequest) ProtoMessage() {}
func (*DeleteHealthMenstruationPersonalInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{18}
}

func (m *DeleteHealthMenstruationPersonalInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest.Unmarshal(m, b)
}
func (m *DeleteHealthMenstruationPersonalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHealthMenstruationPersonalInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest.Merge(m, src)
}
func (m *DeleteHealthMenstruationPersonalInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest.Size(m)
}
func (m *DeleteHealthMenstruationPersonalInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHealthMenstruationPersonalInfoRequest proto.InternalMessageInfo

func (m *DeleteHealthMenstruationPersonalInfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteHealthMenstruationPersonalInfoResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHealthMenstruationPersonalInfoResponse) Reset() {
	*m = DeleteHealthMenstruationPersonalInfoResponse{}
}
func (m *DeleteHealthMenstruationPersonalInfoResponse) String() string {
	return proto.CompactTextString(m)
}
func (*DeleteHealthMenstruationPersonalInfoResponse) ProtoMessage() {}
func (*DeleteHealthMenstruationPersonalInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{19}
}

func (m *DeleteHealthMenstruationPersonalInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse.Unmarshal(m, b)
}
func (m *DeleteHealthMenstruationPersonalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHealthMenstruationPersonalInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse.Merge(m, src)
}
func (m *DeleteHealthMenstruationPersonalInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse.Size(m)
}
func (m *DeleteHealthMenstruationPersonalInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHealthMenstruationPersonalInfoResponse proto.InternalMessageInfo

type ListHealthMenstruationPersonalInfoRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListHealthMenstruationPersonalInfoRequest) Reset() {
	*m = ListHealthMenstruationPersonalInfoRequest{}
}
func (m *ListHealthMenstruationPersonalInfoRequest) String() string {
	return proto.CompactTextString(m)
}
func (*ListHealthMenstruationPersonalInfoRequest) ProtoMessage() {}
func (*ListHealthMenstruationPersonalInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{20}
}

func (m *ListHealthMenstruationPersonalInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest.Unmarshal(m, b)
}
func (m *ListHealthMenstruationPersonalInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest.Marshal(b, m, deterministic)
}
func (m *ListHealthMenstruationPersonalInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest.Merge(m, src)
}
func (m *ListHealthMenstruationPersonalInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest.Size(m)
}
func (m *ListHealthMenstruationPersonalInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHealthMenstruationPersonalInfoRequest proto.InternalMessageInfo

func (m *ListHealthMenstruationPersonalInfoRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListHealthMenstruationPersonalInfoRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListHealthMenstruationPersonalInfoRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListHealthMenstruationPersonalInfoRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListHealthMenstruationPersonalInfoResponse struct {
	Results              []*HealthMenstruationPersonalInfo `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListHealthMenstruationPersonalInfoResponse) Reset() {
	*m = ListHealthMenstruationPersonalInfoResponse{}
}
func (m *ListHealthMenstruationPersonalInfoResponse) String() string {
	return proto.CompactTextString(m)
}
func (*ListHealthMenstruationPersonalInfoResponse) ProtoMessage() {}
func (*ListHealthMenstruationPersonalInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90abfde3e7e610b1, []int{21}
}

func (m *ListHealthMenstruationPersonalInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse.Unmarshal(m, b)
}
func (m *ListHealthMenstruationPersonalInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse.Marshal(b, m, deterministic)
}
func (m *ListHealthMenstruationPersonalInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse.Merge(m, src)
}
func (m *ListHealthMenstruationPersonalInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse.Size(m)
}
func (m *ListHealthMenstruationPersonalInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHealthMenstruationPersonalInfoResponse proto.InternalMessageInfo

func (m *ListHealthMenstruationPersonalInfoResponse) GetResults() []*HealthMenstruationPersonalInfo {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.HealthMenstruationDailyEntry_Type", HealthMenstruationDailyEntry_Type_name, HealthMenstruationDailyEntry_Type_value)
	proto.RegisterType((*HealthMenstruationPersonalInfo)(nil), "model.HealthMenstruationPersonalInfo")
	proto.RegisterType((*HealthMenstruationDailyEntry)(nil), "model.HealthMenstruationDailyEntry")
	proto.RegisterType((*CreateHealthMenstruationDailyEntryRequest)(nil), "model.CreateHealthMenstruationDailyEntryRequest")
	proto.RegisterType((*CreateHealthMenstruationDailyEntryResponse)(nil), "model.CreateHealthMenstruationDailyEntryResponse")
	proto.RegisterType((*ReadHealthMenstruationDailyEntryRequest)(nil), "model.ReadHealthMenstruationDailyEntryRequest")
	proto.RegisterType((*ReadHealthMenstruationDailyEntryResponse)(nil), "model.ReadHealthMenstruationDailyEntryResponse")
	proto.RegisterType((*UpdateHealthMenstruationDailyEntryRequest)(nil), "model.UpdateHealthMenstruationDailyEntryRequest")
	proto.RegisterType((*UpdateHealthMenstruationDailyEntryResponse)(nil), "model.UpdateHealthMenstruationDailyEntryResponse")
	proto.RegisterType((*DeleteHealthMenstruationDailyEntryRequest)(nil), "model.DeleteHealthMenstruationDailyEntryRequest")
	proto.RegisterType((*DeleteHealthMenstruationDailyEntryResponse)(nil), "model.DeleteHealthMenstruationDailyEntryResponse")
	proto.RegisterType((*ListHealthMenstruationDailyEntryRequest)(nil), "model.ListHealthMenstruationDailyEntryRequest")
	proto.RegisterType((*ListHealthMenstruationDailyEntryResponse)(nil), "model.ListHealthMenstruationDailyEntryResponse")
	proto.RegisterType((*CreateHealthMenstruationPersonalInfoRequest)(nil), "model.CreateHealthMenstruationPersonalInfoRequest")
	proto.RegisterType((*CreateHealthMenstruationPersonalInfoResponse)(nil), "model.CreateHealthMenstruationPersonalInfoResponse")
	proto.RegisterType((*ReadHealthMenstruationPersonalInfoRequest)(nil), "model.ReadHealthMenstruationPersonalInfoRequest")
	proto.RegisterType((*ReadHealthMenstruationPersonalInfoResponse)(nil), "model.ReadHealthMenstruationPersonalInfoResponse")
	proto.RegisterType((*UpdateHealthMenstruationPersonalInfoRequest)(nil), "model.UpdateHealthMenstruationPersonalInfoRequest")
	proto.RegisterType((*UpdateHealthMenstruationPersonalInfoResponse)(nil), "model.UpdateHealthMenstruationPersonalInfoResponse")
	proto.RegisterType((*DeleteHealthMenstruationPersonalInfoRequest)(nil), "model.DeleteHealthMenstruationPersonalInfoRequest")
	proto.RegisterType((*DeleteHealthMenstruationPersonalInfoResponse)(nil), "model.DeleteHealthMenstruationPersonalInfoResponse")
	proto.RegisterType((*ListHealthMenstruationPersonalInfoRequest)(nil), "model.ListHealthMenstruationPersonalInfoRequest")
	proto.RegisterType((*ListHealthMenstruationPersonalInfoResponse)(nil), "model.ListHealthMenstruationPersonalInfoResponse")
}

func init() {
	proto.RegisterFile("github.com/kodesmil/ks-model/health.proto", fileDescriptor_90abfde3e7e610b1)
}

var fileDescriptor_90abfde3e7e610b1 = []byte{
	// 1140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0x66, 0xf3, 0xe1, 0xa4, 0x6f, 0xa0, 0x4a, 0xa7, 0x2d, 0x38, 0x56, 0x54, 0xcc, 0x12, 0x54,
	0xe7, 0x6b, 0x37, 0x49, 0xb9, 0xa4, 0x25, 0xaa, 0x12, 0x12, 0x44, 0x50, 0x20, 0x91, 0x9b, 0x72,
	0xe0, 0x62, 0x8d, 0x77, 0x27, 0x9b, 0xa9, 0xc7, 0x33, 0xdb, 0x99, 0x31, 0x62, 0xcf, 0x9c, 0x38,
	0xf1, 0x2f, 0xb8, 0x71, 0xe4, 0x90, 0xfc, 0x04, 0x7e, 0x02, 0xbf, 0x03, 0x71, 0x46, 0xbb, 0x3b,
	0x5e, 0x1c, 0x37, 0xce, 0x8e, 0xa5, 0x80, 0x50, 0x2f, 0x89, 0xed, 0xf7, 0x7d, 0xe6, 0xfd, 0x78,
	0xde, 0x99, 0x67, 0x67, 0x61, 0x39, 0xa2, 0xfa, 0xbc, 0xd7, 0xf6, 0x02, 0xd1, 0xf5, 0x3b, 0x22,
	0x24, 0xaa, 0x4b, 0x99, 0xdf, 0x51, 0xeb, 0x5d, 0x11, 0x12, 0xe6, 0x9f, 0x13, 0xcc, 0xf4, 0xb9,
	0x17, 0x4b, 0xa1, 0x05, 0x9a, 0xce, 0x7e, 0xab, 0xd5, 0x23, 0x21, 0x22, 0x46, 0xfc, 0xec, 0xc7,
	0x76, 0xef, 0xcc, 0x3f, 0xa3, 0x84, 0x85, 0xad, 0x2e, 0x56, 0x9d, 0xdc, 0xb1, 0xf6, 0xe1, 0xb0,
	0x87, 0xa6, 0x5d, 0xa2, 0x34, 0xee, 0xc6, 0xc6, 0x61, 0xd1, 0x38, 0xe0, 0x98, 0xfa, 0x98, 0x73,
	0xa1, 0xb1, 0xa6, 0x82, 0x2b, 0x63, 0x5d, 0xcd, 0xfe, 0x05, 0xeb, 0x11, 0xe1, 0xeb, 0xdf, 0x63,
	0x46, 0x43, 0xac, 0x89, 0xff, 0xc6, 0x07, 0xe3, 0xfc, 0x74, 0x20, 0x7f, 0xca, 0xcf, 0x44, 0x9b,
	0x89, 0x1f, 0x44, 0x4c, 0xb8, 0x3f, 0xb0, 0x48, 0x24, 0x64, 0xd7, 0x17, 0x71, 0x16, 0xc3, 0x4f,
	0xbf, 0x18, 0xec, 0xb6, 0x2d, 0x56, 0x27, 0x31, 0x51, 0xf9, 0x5f, 0x03, 0xfd, 0x6a, 0x14, 0x14,
	0x6b, 0x86, 0xd5, 0x3a, 0x8e, 0xe3, 0x75, 0x2d, 0x04, 0xeb, 0x50, 0xed, 0xbf, 0xee, 0x11, 0x99,
	0xf8, 0x81, 0x60, 0x8c, 0x04, 0x69, 0x0a, 0x2d, 0x11, 0x13, 0x89, 0xb5, 0x90, 0xfd, 0xb5, 0x0e,
	0xec, 0xd7, 0x92, 0x71, 0xe0, 0x4b, 0xa2, 0x44, 0x4f, 0x06, 0xa4, 0xf8, 0x90, 0x2f, 0xe3, 0xfe,
	0x32, 0x01, 0x8f, 0xbe, 0xcc, 0xf8, 0xfa, 0x9a, 0x70, 0xa5, 0x65, 0x2f, 0x6b, 0xea, 0x09, 0x91,
	0x4a, 0x70, 0xcc, 0x0e, 0xf9, 0x99, 0x40, 0x75, 0x98, 0xa0, 0x61, 0xd5, 0xa9, 0x3b, 0x8d, 0xa9,
	0xbd, 0xf9, 0xcb, 0x8b, 0x85, 0x77, 0x01, 0x50, 0x45, 0x11, 0x49, 0x31, 0x6b, 0x38, 0xcd, 0x09,
	0x1a, 0xa2, 0x6d, 0x80, 0x40, 0x12, 0xac, 0x49, 0xd8, 0xc2, 0xba, 0x3a, 0x51, 0x77, 0x1a, 0x73,
	0x5b, 0x35, 0x2f, 0xa7, 0xcb, 0xeb, 0xf3, 0xe9, 0x9d, 0xf6, 0xf9, 0x6c, 0xde, 0x31, 0xde, 0xbb,
	0x3a, 0x85, 0xf6, 0xe2, 0xb0, 0x0f, 0x9d, 0x2c, 0x87, 0x1a, 0xef, 0x5d, 0x8d, 0x36, 0xe1, 0x61,
	0x4c, 0x24, 0x15, 0x61, 0x8b, 0x11, 0x1e, 0xe9, 0xf3, 0x16, 0xe5, 0xad, 0x10, 0x27, 0xaa, 0x3a,
	0x55, 0x77, 0x1a, 0xd3, 0x4d, 0x94, 0x1b, 0x8f, 0x32, 0xdb, 0x21, 0xdf, 0xc7, 0x89, 0x42, 0x3e,
	0x3c, 0x08, 0x92, 0x80, 0x91, 0x61, 0xc4, 0x74, 0x86, 0xb8, 0x97, 0xd9, 0x06, 0x01, 0x4f, 0x67,
	0x2f, 0x2f, 0x16, 0xa6, 0x66, 0x9d, 0xba, 0xe3, 0xfe, 0x3e, 0x09, 0x8b, 0x6f, 0x36, 0x6a, 0x1f,
	0x53, 0x96, 0x1c, 0x70, 0x2d, 0x93, 0xff, 0x6d, 0x9b, 0xd6, 0x60, 0x32, 0xc4, 0x49, 0xd6, 0x94,
	0x9b, 0x31, 0xa9, 0x1b, 0xda, 0x84, 0x07, 0x94, 0x6b, 0xc2, 0x15, 0xd5, 0x49, 0x2b, 0x26, 0x32,
	0x20, 0x5c, 0xe3, 0x88, 0x98, 0x0e, 0xdd, 0x2f, 0x6c, 0x27, 0x85, 0x09, 0x7d, 0x06, 0x53, 0xe9,
	0x90, 0x57, 0x2b, 0x75, 0xa7, 0x71, 0x77, 0xab, 0xe1, 0x65, 0x1b, 0xde, 0xbb, 0xa9, 0x57, 0xde,
	0x69, 0x12, 0x93, 0x66, 0x86, 0x42, 0xef, 0x43, 0xa5, 0x8b, 0x79, 0x0f, 0xb3, 0xea, 0x4c, 0xdd,
	0x69, 0xcc, 0x36, 0xcd, 0x37, 0xe4, 0xc1, 0xfd, 0x36, 0x56, 0x24, 0x6c, 0x09, 0xde, 0x8a, 0x25,
	0x09, 0x69, 0xb6, 0x0d, 0xaa, 0xb3, 0x99, 0xd3, 0xbd, 0xcc, 0x74, 0xcc, 0x4f, 0x0a, 0x83, 0xfb,
	0x11, 0x4c, 0xa5, 0xab, 0x22, 0x80, 0xca, 0xc9, 0x41, 0xf3, 0xf0, 0x78, 0x7f, 0xfe, 0x1d, 0xf4,
	0x1e, 0xdc, 0x39, 0xfe, 0xf6, 0xe5, 0xd1, 0xee, 0xe9, 0xe1, 0xf1, 0x37, 0xf3, 0xce, 0x00, 0x99,
	0xaf, 0x60, 0xf9, 0xf3, 0xac, 0xb7, 0x37, 0x65, 0xd9, 0x24, 0xaf, 0x7b, 0x44, 0x69, 0xb4, 0x03,
	0x33, 0x31, 0x4e, 0x98, 0xc0, 0x39, 0xbb, 0x73, 0x5b, 0x1f, 0x5b, 0x94, 0xd8, 0xec, 0x63, 0x5c,
	0x0a, 0x2b, 0x36, 0xb1, 0x54, 0x2c, 0xb8, 0x22, 0xe8, 0x19, 0x54, 0x24, 0x51, 0x3d, 0xa6, 0xc7,
	0x89, 0x65, 0x20, 0xee, 0x36, 0x3c, 0x6e, 0x12, 0x1c, 0xda, 0x14, 0x75, 0xf7, 0x9f, 0x69, 0x4d,
	0x67, 0xd3, 0x8d, 0xa0, 0x51, 0x0e, 0xbd, 0x8d, 0x1c, 0x5f, 0xc1, 0xf2, 0xcb, 0x6c, 0x36, 0xff,
	0x9b, 0xd6, 0xdb, 0xc4, 0xba, 0x8d, 0xb2, 0x9e, 0xc1, 0xf2, 0x3e, 0x61, 0xc4, 0xae, 0xac, 0xe1,
	0xe6, 0xaf, 0xc1, 0x8a, 0x0d, 0x38, 0xcf, 0xd3, 0xfd, 0xd3, 0x81, 0xc7, 0x47, 0x54, 0x69, 0x9b,
	0x48, 0x3e, 0x54, 0xce, 0x28, 0xd3, 0x44, 0x9a, 0x9a, 0x3e, 0xf0, 0xfa, 0x5a, 0xe1, 0xe1, 0x98,
	0x7a, 0x5f, 0x64, 0x36, 0xca, 0xa3, 0xa6, 0x71, 0x43, 0x1b, 0x30, 0x2b, 0x64, 0x48, 0x64, 0xab,
	0x9d, 0x98, 0x13, 0xea, 0xe1, 0x55, 0xc8, 0x0b, 0x21, 0x75, 0x0a, 0x98, 0xc9, 0xdc, 0xf6, 0x12,
	0xf4, 0x69, 0x1a, 0x82, 0xb0, 0x50, 0x99, 0x63, 0x69, 0x71, 0x38, 0x04, 0x61, 0xe1, 0x0b, 0x62,
	0x64, 0xac, 0x69, 0x7c, 0xd1, 0x06, 0x54, 0x62, 0x1c, 0x51, 0x1e, 0x99, 0x83, 0xa9, 0x7a, 0x15,
	0x75, 0x92, 0xda, 0x70, 0x8e, 0xc8, 0xfd, 0x5c, 0x0a, 0x8d, 0xf2, 0xaa, 0x0d, 0x95, 0x3b, 0x30,
	0x93, 0xf3, 0xa2, 0xaa, 0x4e, 0x7d, 0xd2, 0x7a, 0x6e, 0x0c, 0xc6, 0xe5, 0xb0, 0x3a, 0x6a, 0xcb,
	0x0e, 0x2a, 0x63, 0xbf, 0xc9, 0xcf, 0x87, 0xa7, 0xf4, 0x93, 0x91, 0xd1, 0xae, 0xc0, 0x8b, 0x39,
	0xed, 0xc2, 0x9a, 0x5d, 0xbc, 0xa2, 0xbc, 0xab, 0x93, 0x6a, 0x19, 0x6f, 0x60, 0x56, 0xaf, 0xdf,
	0xeb, 0xd7, 0x15, 0x37, 0x3c, 0xab, 0x1d, 0x58, 0xb1, 0x01, 0xdf, 0x4e, 0xa6, 0x1c, 0x56, 0x47,
	0x6d, 0xe0, 0x7f, 0x8b, 0x08, 0xbb, 0x78, 0xb7, 0x53, 0xde, 0x0e, 0xac, 0x8e, 0xda, 0xf7, 0x36,
	0x54, 0x78, 0xb0, 0x66, 0x07, 0x37, 0x07, 0xc7, 0x5f, 0x0e, 0x2c, 0x5f, 0xbf, 0x85, 0xae, 0x8b,
	0xf6, 0x16, 0x1d, 0x1d, 0x5d, 0x58, 0xb1, 0xa9, 0xdb, 0x90, 0xfa, 0x7c, 0xf8, 0xf0, 0xb0, 0x9d,
	0x22, 0x83, 0xda, 0xfa, 0x63, 0x0e, 0x2a, 0xb9, 0x2f, 0xfa, 0xc9, 0x01, 0xb7, 0x5c, 0xfd, 0xd1,
	0x86, 0x89, 0x60, 0xfd, 0x50, 0x52, 0xdb, 0x1c, 0x03, 0x61, 0xea, 0xfa, 0xd1, 0x81, 0x7a, 0x99,
	0xc6, 0x23, 0xcf, 0xac, 0x6b, 0xf9, 0x1c, 0x51, 0xf3, 0xad, 0xfd, 0x4d, 0x16, 0x69, 0x47, 0xca,
	0x45, 0xb9, 0xe8, 0x88, 0xf5, 0xb3, 0x42, 0xd1, 0x91, 0x31, 0x14, 0xff, 0x57, 0x07, 0xdc, 0x72,
	0xe1, 0x2d, 0x72, 0xb1, 0x16, 0xf8, 0x22, 0x97, 0x31, 0x54, 0xdd, 0xbd, 0xbc, 0x58, 0x78, 0x54,
	0x72, 0xc5, 0x48, 0x19, 0x2c, 0xd3, 0xc0, 0x82, 0x41, 0xcb, 0x47, 0x84, 0x82, 0x41, 0x6b, 0x71,
	0xfd, 0xd9, 0x81, 0x25, 0x1b, 0xb9, 0x42, 0x5b, 0x25, 0x33, 0x7a, 0xcd, 0xa9, 0x53, 0x7b, 0x32,
	0x16, 0x66, 0x60, 0xa6, 0xca, 0x45, 0xa9, 0xe0, 0xd1, 0x5a, 0xfc, 0x0a, 0x1e, 0xc7, 0x50, 0xbc,
	0xb4, 0x3b, 0x36, 0x1a, 0x52, 0x74, 0x67, 0x0c, 0x81, 0x2b, 0xba, 0x33, 0x96, 0x48, 0xfd, 0xe6,
	0xc0, 0x92, 0x8d, 0x4e, 0x14, 0x19, 0x8d, 0xa1, 0x49, 0x45, 0x46, 0x63, 0x09, 0xd1, 0xd2, 0xe5,
	0xc5, 0x42, 0xbd, 0xf4, 0xbd, 0x43, 0xca, 0x6a, 0xf9, 0xb1, 0x5d, 0xb0, 0x6a, 0xad, 0x6c, 0x05,
	0xab, 0xf6, 0x9a, 0x50, 0x33, 0x57, 0xc7, 0xaa, 0xb3, 0xb7, 0xf1, 0x9d, 0x37, 0xe2, 0xe5, 0x57,
	0x1b, 0x07, 0x1d, 0xc2, 0x43, 0x3f, 0xbd, 0x23, 0x4b, 0x8e, 0x99, 0x1f, 0x77, 0x22, 0x3f, 0x6e,
	0xb7, 0x2b, 0xd9, 0x5d, 0xfb, 0xc9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xff, 0xde, 0x80, 0x2c,
	0x35, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HealthClient interface {
	CreateHealthMenstruationDailyEntry(ctx context.Context, in *CreateHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*CreateHealthMenstruationDailyEntryResponse, error)
	ReadHealthMenstruationDailyEntry(ctx context.Context, in *ReadHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*ReadHealthMenstruationDailyEntryResponse, error)
	UpdateHealthMenstruationDailyEntry(ctx context.Context, in *UpdateHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*UpdateHealthMenstruationDailyEntryResponse, error)
	DeleteHealthMenstruationDailyEntry(ctx context.Context, in *DeleteHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*DeleteHealthMenstruationDailyEntryResponse, error)
	ListHealthMenstruationDailyEntry(ctx context.Context, in *ListHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*ListHealthMenstruationDailyEntryResponse, error)
	CreateHealthMenstruationPersonalInfo(ctx context.Context, in *CreateHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*CreateHealthMenstruationPersonalInfoResponse, error)
	ReadHealthMenstruationPersonalInfo(ctx context.Context, in *ReadHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*ReadHealthMenstruationPersonalInfoResponse, error)
	UpdateHealthMenstruationPersonalInfo(ctx context.Context, in *UpdateHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*UpdateHealthMenstruationPersonalInfoResponse, error)
	DeleteHealthMenstruationPersonalInfo(ctx context.Context, in *DeleteHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*DeleteHealthMenstruationPersonalInfoResponse, error)
	ListHealthMenstruationPersonalInfo(ctx context.Context, in *ListHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*ListHealthMenstruationPersonalInfoResponse, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) CreateHealthMenstruationDailyEntry(ctx context.Context, in *CreateHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*CreateHealthMenstruationDailyEntryResponse, error) {
	out := new(CreateHealthMenstruationDailyEntryResponse)
	err := c.cc.Invoke(ctx, "/model.Health/CreateHealthMenstruationDailyEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ReadHealthMenstruationDailyEntry(ctx context.Context, in *ReadHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*ReadHealthMenstruationDailyEntryResponse, error) {
	out := new(ReadHealthMenstruationDailyEntryResponse)
	err := c.cc.Invoke(ctx, "/model.Health/ReadHealthMenstruationDailyEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) UpdateHealthMenstruationDailyEntry(ctx context.Context, in *UpdateHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*UpdateHealthMenstruationDailyEntryResponse, error) {
	out := new(UpdateHealthMenstruationDailyEntryResponse)
	err := c.cc.Invoke(ctx, "/model.Health/UpdateHealthMenstruationDailyEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) DeleteHealthMenstruationDailyEntry(ctx context.Context, in *DeleteHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*DeleteHealthMenstruationDailyEntryResponse, error) {
	out := new(DeleteHealthMenstruationDailyEntryResponse)
	err := c.cc.Invoke(ctx, "/model.Health/DeleteHealthMenstruationDailyEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ListHealthMenstruationDailyEntry(ctx context.Context, in *ListHealthMenstruationDailyEntryRequest, opts ...grpc.CallOption) (*ListHealthMenstruationDailyEntryResponse, error) {
	out := new(ListHealthMenstruationDailyEntryResponse)
	err := c.cc.Invoke(ctx, "/model.Health/ListHealthMenstruationDailyEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) CreateHealthMenstruationPersonalInfo(ctx context.Context, in *CreateHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*CreateHealthMenstruationPersonalInfoResponse, error) {
	out := new(CreateHealthMenstruationPersonalInfoResponse)
	err := c.cc.Invoke(ctx, "/model.Health/CreateHealthMenstruationPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ReadHealthMenstruationPersonalInfo(ctx context.Context, in *ReadHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*ReadHealthMenstruationPersonalInfoResponse, error) {
	out := new(ReadHealthMenstruationPersonalInfoResponse)
	err := c.cc.Invoke(ctx, "/model.Health/ReadHealthMenstruationPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) UpdateHealthMenstruationPersonalInfo(ctx context.Context, in *UpdateHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*UpdateHealthMenstruationPersonalInfoResponse, error) {
	out := new(UpdateHealthMenstruationPersonalInfoResponse)
	err := c.cc.Invoke(ctx, "/model.Health/UpdateHealthMenstruationPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) DeleteHealthMenstruationPersonalInfo(ctx context.Context, in *DeleteHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*DeleteHealthMenstruationPersonalInfoResponse, error) {
	out := new(DeleteHealthMenstruationPersonalInfoResponse)
	err := c.cc.Invoke(ctx, "/model.Health/DeleteHealthMenstruationPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) ListHealthMenstruationPersonalInfo(ctx context.Context, in *ListHealthMenstruationPersonalInfoRequest, opts ...grpc.CallOption) (*ListHealthMenstruationPersonalInfoResponse, error) {
	out := new(ListHealthMenstruationPersonalInfoResponse)
	err := c.cc.Invoke(ctx, "/model.Health/ListHealthMenstruationPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
type HealthServer interface {
	CreateHealthMenstruationDailyEntry(context.Context, *CreateHealthMenstruationDailyEntryRequest) (*CreateHealthMenstruationDailyEntryResponse, error)
	ReadHealthMenstruationDailyEntry(context.Context, *ReadHealthMenstruationDailyEntryRequest) (*ReadHealthMenstruationDailyEntryResponse, error)
	UpdateHealthMenstruationDailyEntry(context.Context, *UpdateHealthMenstruationDailyEntryRequest) (*UpdateHealthMenstruationDailyEntryResponse, error)
	DeleteHealthMenstruationDailyEntry(context.Context, *DeleteHealthMenstruationDailyEntryRequest) (*DeleteHealthMenstruationDailyEntryResponse, error)
	ListHealthMenstruationDailyEntry(context.Context, *ListHealthMenstruationDailyEntryRequest) (*ListHealthMenstruationDailyEntryResponse, error)
	CreateHealthMenstruationPersonalInfo(context.Context, *CreateHealthMenstruationPersonalInfoRequest) (*CreateHealthMenstruationPersonalInfoResponse, error)
	ReadHealthMenstruationPersonalInfo(context.Context, *ReadHealthMenstruationPersonalInfoRequest) (*ReadHealthMenstruationPersonalInfoResponse, error)
	UpdateHealthMenstruationPersonalInfo(context.Context, *UpdateHealthMenstruationPersonalInfoRequest) (*UpdateHealthMenstruationPersonalInfoResponse, error)
	DeleteHealthMenstruationPersonalInfo(context.Context, *DeleteHealthMenstruationPersonalInfoRequest) (*DeleteHealthMenstruationPersonalInfoResponse, error)
	ListHealthMenstruationPersonalInfo(context.Context, *ListHealthMenstruationPersonalInfoRequest) (*ListHealthMenstruationPersonalInfoResponse, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_CreateHealthMenstruationDailyEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHealthMenstruationDailyEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).CreateHealthMenstruationDailyEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/CreateHealthMenstruationDailyEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).CreateHealthMenstruationDailyEntry(ctx, req.(*CreateHealthMenstruationDailyEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ReadHealthMenstruationDailyEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHealthMenstruationDailyEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ReadHealthMenstruationDailyEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/ReadHealthMenstruationDailyEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ReadHealthMenstruationDailyEntry(ctx, req.(*ReadHealthMenstruationDailyEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_UpdateHealthMenstruationDailyEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHealthMenstruationDailyEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).UpdateHealthMenstruationDailyEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/UpdateHealthMenstruationDailyEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).UpdateHealthMenstruationDailyEntry(ctx, req.(*UpdateHealthMenstruationDailyEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_DeleteHealthMenstruationDailyEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHealthMenstruationDailyEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).DeleteHealthMenstruationDailyEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/DeleteHealthMenstruationDailyEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).DeleteHealthMenstruationDailyEntry(ctx, req.(*DeleteHealthMenstruationDailyEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ListHealthMenstruationDailyEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHealthMenstruationDailyEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListHealthMenstruationDailyEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/ListHealthMenstruationDailyEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListHealthMenstruationDailyEntry(ctx, req.(*ListHealthMenstruationDailyEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_CreateHealthMenstruationPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHealthMenstruationPersonalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).CreateHealthMenstruationPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/CreateHealthMenstruationPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).CreateHealthMenstruationPersonalInfo(ctx, req.(*CreateHealthMenstruationPersonalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ReadHealthMenstruationPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadHealthMenstruationPersonalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ReadHealthMenstruationPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/ReadHealthMenstruationPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ReadHealthMenstruationPersonalInfo(ctx, req.(*ReadHealthMenstruationPersonalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_UpdateHealthMenstruationPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHealthMenstruationPersonalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).UpdateHealthMenstruationPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/UpdateHealthMenstruationPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).UpdateHealthMenstruationPersonalInfo(ctx, req.(*UpdateHealthMenstruationPersonalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_DeleteHealthMenstruationPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHealthMenstruationPersonalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).DeleteHealthMenstruationPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/DeleteHealthMenstruationPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).DeleteHealthMenstruationPersonalInfo(ctx, req.(*DeleteHealthMenstruationPersonalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_ListHealthMenstruationPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHealthMenstruationPersonalInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).ListHealthMenstruationPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Health/ListHealthMenstruationPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).ListHealthMenstruationPersonalInfo(ctx, req.(*ListHealthMenstruationPersonalInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHealthMenstruationDailyEntry",
			Handler:    _Health_CreateHealthMenstruationDailyEntry_Handler,
		},
		{
			MethodName: "ReadHealthMenstruationDailyEntry",
			Handler:    _Health_ReadHealthMenstruationDailyEntry_Handler,
		},
		{
			MethodName: "UpdateHealthMenstruationDailyEntry",
			Handler:    _Health_UpdateHealthMenstruationDailyEntry_Handler,
		},
		{
			MethodName: "DeleteHealthMenstruationDailyEntry",
			Handler:    _Health_DeleteHealthMenstruationDailyEntry_Handler,
		},
		{
			MethodName: "ListHealthMenstruationDailyEntry",
			Handler:    _Health_ListHealthMenstruationDailyEntry_Handler,
		},
		{
			MethodName: "CreateHealthMenstruationPersonalInfo",
			Handler:    _Health_CreateHealthMenstruationPersonalInfo_Handler,
		},
		{
			MethodName: "ReadHealthMenstruationPersonalInfo",
			Handler:    _Health_ReadHealthMenstruationPersonalInfo_Handler,
		},
		{
			MethodName: "UpdateHealthMenstruationPersonalInfo",
			Handler:    _Health_UpdateHealthMenstruationPersonalInfo_Handler,
		},
		{
			MethodName: "DeleteHealthMenstruationPersonalInfo",
			Handler:    _Health_DeleteHealthMenstruationPersonalInfo_Handler,
		},
		{
			MethodName: "ListHealthMenstruationPersonalInfo",
			Handler:    _Health_ListHealthMenstruationPersonalInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kodesmil/ks-model/health.proto",
}
