
version: latest
docker:
  registry: kodesmil

#### Values that will be populated from env vaues
env: "minikube"
zone: "local"

image:
  pullPolicy: IfNotPresent


db:
  username: postgres
  server: "{{ include \"chart.fullname\" . }}-postgres.{{ .Release.Namespace }}"
  password: postgres

postgres:
  name: postgres
  image: postgres
  version: "10.5"
  imagePullPolicy: IfNotPresent
  port: "5432"


app:
  namespace: "go-patient-registry-{{ .Values.env }}"
  httpPort: 8080
  grpcPort: 9090

secrets:
  enabled: true
