// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kodesmil/ks-model/journal.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JournalSubject_Type int32

const (
	JournalSubject_ACTIVITY JournalSubject_Type = 0
	JournalSubject_SYMPTOM  JournalSubject_Type = 1
)

var JournalSubject_Type_name = map[int32]string{
	0: "ACTIVITY",
	1: "SYMPTOM",
}

var JournalSubject_Type_value = map[string]int32{
	"ACTIVITY": 0,
	"SYMPTOM":  1,
}

func (x JournalSubject_Type) String() string {
	return proto.EnumName(JournalSubject_Type_name, int32(x))
}

func (JournalSubject_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{0, 0}
}

type JournalEntry_Severity int32

const (
	JournalEntry_NONE JournalEntry_Severity = 0
	JournalEntry_LOW  JournalEntry_Severity = 1
	JournalEntry_MID  JournalEntry_Severity = 2
	JournalEntry_HIGH JournalEntry_Severity = 3
)

var JournalEntry_Severity_name = map[int32]string{
	0: "NONE",
	1: "LOW",
	2: "MID",
	3: "HIGH",
}

var JournalEntry_Severity_value = map[string]int32{
	"NONE": 0,
	"LOW":  1,
	"MID":  2,
	"HIGH": 3,
}

func (x JournalEntry_Severity) String() string {
	return proto.EnumName(JournalEntry_Severity_name, int32(x))
}

func (JournalEntry_Severity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{1, 0}
}

type JournalSubject struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string               `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 JournalSubject_Type  `protobuf:"varint,4,opt,name=type,proto3,enum=model.JournalSubject_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *JournalSubject) Reset()         { *m = JournalSubject{} }
func (m *JournalSubject) String() string { return proto.CompactTextString(m) }
func (*JournalSubject) ProtoMessage()    {}
func (*JournalSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{0}
}

func (m *JournalSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalSubject.Unmarshal(m, b)
}
func (m *JournalSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalSubject.Marshal(b, m, deterministic)
}
func (m *JournalSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalSubject.Merge(m, src)
}
func (m *JournalSubject) XXX_Size() int {
	return xxx_messageInfo_JournalSubject.Size(m)
}
func (m *JournalSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalSubject.DiscardUnknown(m)
}

var xxx_messageInfo_JournalSubject proto.InternalMessageInfo

func (m *JournalSubject) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *JournalSubject) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *JournalSubject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JournalSubject) GetType() JournalSubject_Type {
	if m != nil {
		return m.Type
	}
	return JournalSubject_ACTIVITY
}

type JournalEntry struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity             JournalEntry_Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=model.JournalEntry_Severity" json:"severity,omitempty"`
	Note                 string                `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	JournalSubjectId     int64                 `protobuf:"varint,5,opt,name=journal_subject_id,json=journalSubjectId,proto3" json:"journal_subject_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *JournalEntry) Reset()         { *m = JournalEntry{} }
func (m *JournalEntry) String() string { return proto.CompactTextString(m) }
func (*JournalEntry) ProtoMessage()    {}
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{1}
}

func (m *JournalEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JournalEntry.Unmarshal(m, b)
}
func (m *JournalEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JournalEntry.Marshal(b, m, deterministic)
}
func (m *JournalEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JournalEntry.Merge(m, src)
}
func (m *JournalEntry) XXX_Size() int {
	return xxx_messageInfo_JournalEntry.Size(m)
}
func (m *JournalEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_JournalEntry.DiscardUnknown(m)
}

var xxx_messageInfo_JournalEntry proto.InternalMessageInfo

func (m *JournalEntry) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *JournalEntry) GetSeverity() JournalEntry_Severity {
	if m != nil {
		return m.Severity
	}
	return JournalEntry_NONE
}

func (m *JournalEntry) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *JournalEntry) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *JournalEntry) GetJournalSubjectId() int64 {
	if m != nil {
		return m.JournalSubjectId
	}
	return 0
}

type CreateJournalEntryRequest struct {
	Payload              *JournalEntry `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateJournalEntryRequest) Reset()         { *m = CreateJournalEntryRequest{} }
func (m *CreateJournalEntryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateJournalEntryRequest) ProtoMessage()    {}
func (*CreateJournalEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{2}
}

func (m *CreateJournalEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJournalEntryRequest.Unmarshal(m, b)
}
func (m *CreateJournalEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJournalEntryRequest.Marshal(b, m, deterministic)
}
func (m *CreateJournalEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJournalEntryRequest.Merge(m, src)
}
func (m *CreateJournalEntryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateJournalEntryRequest.Size(m)
}
func (m *CreateJournalEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJournalEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJournalEntryRequest proto.InternalMessageInfo

func (m *CreateJournalEntryRequest) GetPayload() *JournalEntry {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateJournalEntryResponse struct {
	Result               *JournalEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateJournalEntryResponse) Reset()         { *m = CreateJournalEntryResponse{} }
func (m *CreateJournalEntryResponse) String() string { return proto.CompactTextString(m) }
func (*CreateJournalEntryResponse) ProtoMessage()    {}
func (*CreateJournalEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{3}
}

func (m *CreateJournalEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateJournalEntryResponse.Unmarshal(m, b)
}
func (m *CreateJournalEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateJournalEntryResponse.Marshal(b, m, deterministic)
}
func (m *CreateJournalEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateJournalEntryResponse.Merge(m, src)
}
func (m *CreateJournalEntryResponse) XXX_Size() int {
	return xxx_messageInfo_CreateJournalEntryResponse.Size(m)
}
func (m *CreateJournalEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateJournalEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateJournalEntryResponse proto.InternalMessageInfo

func (m *CreateJournalEntryResponse) GetResult() *JournalEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadJournalEntryRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadJournalEntryRequest) Reset()         { *m = ReadJournalEntryRequest{} }
func (m *ReadJournalEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ReadJournalEntryRequest) ProtoMessage()    {}
func (*ReadJournalEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{4}
}

func (m *ReadJournalEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJournalEntryRequest.Unmarshal(m, b)
}
func (m *ReadJournalEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJournalEntryRequest.Marshal(b, m, deterministic)
}
func (m *ReadJournalEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJournalEntryRequest.Merge(m, src)
}
func (m *ReadJournalEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ReadJournalEntryRequest.Size(m)
}
func (m *ReadJournalEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJournalEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJournalEntryRequest proto.InternalMessageInfo

func (m *ReadJournalEntryRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadJournalEntryResponse struct {
	Result               *JournalEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadJournalEntryResponse) Reset()         { *m = ReadJournalEntryResponse{} }
func (m *ReadJournalEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ReadJournalEntryResponse) ProtoMessage()    {}
func (*ReadJournalEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{5}
}

func (m *ReadJournalEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadJournalEntryResponse.Unmarshal(m, b)
}
func (m *ReadJournalEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadJournalEntryResponse.Marshal(b, m, deterministic)
}
func (m *ReadJournalEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadJournalEntryResponse.Merge(m, src)
}
func (m *ReadJournalEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ReadJournalEntryResponse.Size(m)
}
func (m *ReadJournalEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadJournalEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadJournalEntryResponse proto.InternalMessageInfo

func (m *ReadJournalEntryResponse) GetResult() *JournalEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateJournalEntryRequest struct {
	Payload              *JournalEntry `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateJournalEntryRequest) Reset()         { *m = UpdateJournalEntryRequest{} }
func (m *UpdateJournalEntryRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJournalEntryRequest) ProtoMessage()    {}
func (*UpdateJournalEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{6}
}

func (m *UpdateJournalEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJournalEntryRequest.Unmarshal(m, b)
}
func (m *UpdateJournalEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJournalEntryRequest.Marshal(b, m, deterministic)
}
func (m *UpdateJournalEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJournalEntryRequest.Merge(m, src)
}
func (m *UpdateJournalEntryRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJournalEntryRequest.Size(m)
}
func (m *UpdateJournalEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJournalEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJournalEntryRequest proto.InternalMessageInfo

func (m *UpdateJournalEntryRequest) GetPayload() *JournalEntry {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateJournalEntryResponse struct {
	Result               *JournalEntry `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateJournalEntryResponse) Reset()         { *m = UpdateJournalEntryResponse{} }
func (m *UpdateJournalEntryResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateJournalEntryResponse) ProtoMessage()    {}
func (*UpdateJournalEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{7}
}

func (m *UpdateJournalEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJournalEntryResponse.Unmarshal(m, b)
}
func (m *UpdateJournalEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJournalEntryResponse.Marshal(b, m, deterministic)
}
func (m *UpdateJournalEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJournalEntryResponse.Merge(m, src)
}
func (m *UpdateJournalEntryResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateJournalEntryResponse.Size(m)
}
func (m *UpdateJournalEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJournalEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJournalEntryResponse proto.InternalMessageInfo

func (m *UpdateJournalEntryResponse) GetResult() *JournalEntry {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteJournalEntryRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteJournalEntryRequest) Reset()         { *m = DeleteJournalEntryRequest{} }
func (m *DeleteJournalEntryRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJournalEntryRequest) ProtoMessage()    {}
func (*DeleteJournalEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{8}
}

func (m *DeleteJournalEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJournalEntryRequest.Unmarshal(m, b)
}
func (m *DeleteJournalEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJournalEntryRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJournalEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJournalEntryRequest.Merge(m, src)
}
func (m *DeleteJournalEntryRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJournalEntryRequest.Size(m)
}
func (m *DeleteJournalEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJournalEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJournalEntryRequest proto.InternalMessageInfo

func (m *DeleteJournalEntryRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteJournalEntryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJournalEntryResponse) Reset()         { *m = DeleteJournalEntryResponse{} }
func (m *DeleteJournalEntryResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJournalEntryResponse) ProtoMessage()    {}
func (*DeleteJournalEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{9}
}

func (m *DeleteJournalEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJournalEntryResponse.Unmarshal(m, b)
}
func (m *DeleteJournalEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJournalEntryResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJournalEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJournalEntryResponse.Merge(m, src)
}
func (m *DeleteJournalEntryResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJournalEntryResponse.Size(m)
}
func (m *DeleteJournalEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJournalEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJournalEntryResponse proto.InternalMessageInfo

type ListJournalEntryRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListJournalEntryRequest) Reset()         { *m = ListJournalEntryRequest{} }
func (m *ListJournalEntryRequest) String() string { return proto.CompactTextString(m) }
func (*ListJournalEntryRequest) ProtoMessage()    {}
func (*ListJournalEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{10}
}

func (m *ListJournalEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJournalEntryRequest.Unmarshal(m, b)
}
func (m *ListJournalEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJournalEntryRequest.Marshal(b, m, deterministic)
}
func (m *ListJournalEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJournalEntryRequest.Merge(m, src)
}
func (m *ListJournalEntryRequest) XXX_Size() int {
	return xxx_messageInfo_ListJournalEntryRequest.Size(m)
}
func (m *ListJournalEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJournalEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJournalEntryRequest proto.InternalMessageInfo

func (m *ListJournalEntryRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListJournalEntryRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListJournalEntryRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListJournalEntryRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListJournalEntryResponse struct {
	Results              []*JournalEntry `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListJournalEntryResponse) Reset()         { *m = ListJournalEntryResponse{} }
func (m *ListJournalEntryResponse) String() string { return proto.CompactTextString(m) }
func (*ListJournalEntryResponse) ProtoMessage()    {}
func (*ListJournalEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{11}
}

func (m *ListJournalEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJournalEntryResponse.Unmarshal(m, b)
}
func (m *ListJournalEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJournalEntryResponse.Marshal(b, m, deterministic)
}
func (m *ListJournalEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJournalEntryResponse.Merge(m, src)
}
func (m *ListJournalEntryResponse) XXX_Size() int {
	return xxx_messageInfo_ListJournalEntryResponse.Size(m)
}
func (m *ListJournalEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJournalEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJournalEntryResponse proto.InternalMessageInfo

func (m *ListJournalEntryResponse) GetResults() []*JournalEntry {
	if m != nil {
		return m.Results
	}
	return nil
}

type ListJournalSubjectRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListJournalSubjectRequest) Reset()         { *m = ListJournalSubjectRequest{} }
func (m *ListJournalSubjectRequest) String() string { return proto.CompactTextString(m) }
func (*ListJournalSubjectRequest) ProtoMessage()    {}
func (*ListJournalSubjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{12}
}

func (m *ListJournalSubjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJournalSubjectRequest.Unmarshal(m, b)
}
func (m *ListJournalSubjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJournalSubjectRequest.Marshal(b, m, deterministic)
}
func (m *ListJournalSubjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJournalSubjectRequest.Merge(m, src)
}
func (m *ListJournalSubjectRequest) XXX_Size() int {
	return xxx_messageInfo_ListJournalSubjectRequest.Size(m)
}
func (m *ListJournalSubjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJournalSubjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListJournalSubjectRequest proto.InternalMessageInfo

func (m *ListJournalSubjectRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListJournalSubjectRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListJournalSubjectRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListJournalSubjectRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListJournalSubjectResponse struct {
	Results              []*JournalSubject `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListJournalSubjectResponse) Reset()         { *m = ListJournalSubjectResponse{} }
func (m *ListJournalSubjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListJournalSubjectResponse) ProtoMessage()    {}
func (*ListJournalSubjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f15f294d657bf37c, []int{13}
}

func (m *ListJournalSubjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListJournalSubjectResponse.Unmarshal(m, b)
}
func (m *ListJournalSubjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListJournalSubjectResponse.Marshal(b, m, deterministic)
}
func (m *ListJournalSubjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListJournalSubjectResponse.Merge(m, src)
}
func (m *ListJournalSubjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListJournalSubjectResponse.Size(m)
}
func (m *ListJournalSubjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListJournalSubjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListJournalSubjectResponse proto.InternalMessageInfo

func (m *ListJournalSubjectResponse) GetResults() []*JournalSubject {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("model.JournalSubject_Type", JournalSubject_Type_name, JournalSubject_Type_value)
	proto.RegisterEnum("model.JournalEntry_Severity", JournalEntry_Severity_name, JournalEntry_Severity_value)
	proto.RegisterType((*JournalSubject)(nil), "model.JournalSubject")
	proto.RegisterType((*JournalEntry)(nil), "model.JournalEntry")
	proto.RegisterType((*CreateJournalEntryRequest)(nil), "model.CreateJournalEntryRequest")
	proto.RegisterType((*CreateJournalEntryResponse)(nil), "model.CreateJournalEntryResponse")
	proto.RegisterType((*ReadJournalEntryRequest)(nil), "model.ReadJournalEntryRequest")
	proto.RegisterType((*ReadJournalEntryResponse)(nil), "model.ReadJournalEntryResponse")
	proto.RegisterType((*UpdateJournalEntryRequest)(nil), "model.UpdateJournalEntryRequest")
	proto.RegisterType((*UpdateJournalEntryResponse)(nil), "model.UpdateJournalEntryResponse")
	proto.RegisterType((*DeleteJournalEntryRequest)(nil), "model.DeleteJournalEntryRequest")
	proto.RegisterType((*DeleteJournalEntryResponse)(nil), "model.DeleteJournalEntryResponse")
	proto.RegisterType((*ListJournalEntryRequest)(nil), "model.ListJournalEntryRequest")
	proto.RegisterType((*ListJournalEntryResponse)(nil), "model.ListJournalEntryResponse")
	proto.RegisterType((*ListJournalSubjectRequest)(nil), "model.ListJournalSubjectRequest")
	proto.RegisterType((*ListJournalSubjectResponse)(nil), "model.ListJournalSubjectResponse")
}

func init() {
	proto.RegisterFile("github.com/kodesmil/ks-model/journal.proto", fileDescriptor_f15f294d657bf37c)
}

var fileDescriptor_f15f294d657bf37c = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xae, 0x6c, 0xd7, 0x71, 0x4f, 0x8a, 0xcc, 0xe0, 0x50, 0xc4, 0x16, 0x82, 0xd5, 0x15, 0x50,
	0x2c, 0x58, 0x67, 0x29, 0xf0, 0x06, 0x6c, 0xcd, 0xd5, 0x9a, 0x36, 0x4b, 0x9d, 0xd5, 0x4d, 0x21,
	0x7b, 0x1b, 0xba, 0x1b, 0x83, 0x96, 0x8e, 0x3d, 0xc6, 0xb2, 0xc8, 0x92, 0x74, 0x31, 0x3f, 0xd3,
	0x9e, 0x20, 0x7e, 0x84, 0x3d, 0xc7, 0xb0, 0xe7, 0x18, 0x24, 0xd1, 0x5a, 0x9c, 0x58, 0x59, 0x10,
	0xec, 0x6a, 0x37, 0x09, 0x45, 0x7e, 0xe7, 0x3b, 0x7f, 0xfc, 0x0e, 0x0d, 0x5f, 0x4c, 0x98, 0xfe,
	0x75, 0x3e, 0x72, 0x03, 0x3e, 0xf3, 0xa6, 0x3c, 0x44, 0x35, 0x63, 0x91, 0x37, 0x55, 0xed, 0x19,
	0x0f, 0x31, 0xf2, 0xce, 0xf9, 0x5c, 0xc6, 0x34, 0x72, 0x85, 0xe4, 0x9a, 0x93, 0xfb, 0xe9, 0xa6,
	0xdd, 0x9a, 0x70, 0x3e, 0x89, 0xd0, 0x4b, 0x37, 0x47, 0xf3, 0xb1, 0x37, 0x66, 0x18, 0x85, 0xc3,
	0x19, 0x55, 0xd3, 0x0c, 0x68, 0x3f, 0xbe, 0x8a, 0xd0, 0x6c, 0x86, 0x4a, 0xd3, 0x99, 0x30, 0x80,
	0x3d, 0x03, 0xa0, 0x82, 0x79, 0x34, 0x8e, 0xb9, 0xa6, 0x9a, 0xf1, 0x58, 0x99, 0xd3, 0x67, 0xe9,
	0xbf, 0xa0, 0x3d, 0xc1, 0xb8, 0xfd, 0x91, 0x46, 0x2c, 0xa4, 0x1a, 0xbd, 0x6b, 0x0b, 0x03, 0x3e,
	0xbc, 0x94, 0x00, 0x8b, 0xc7, 0x7c, 0x14, 0xf1, 0xdf, 0xb8, 0xc0, 0xd8, 0xbb, 0x44, 0x32, 0xe1,
	0x72, 0xe6, 0x71, 0x91, 0xfa, 0xf0, 0x92, 0x0f, 0x63, 0xfb, 0xfc, 0xb6, 0xb6, 0x7a, 0x21, 0x50,
	0x65, 0x7f, 0x8d, 0xe9, 0x69, 0x91, 0x29, 0xd5, 0x11, 0x55, 0x6d, 0x2a, 0x44, 0x5b, 0x73, 0x1e,
	0x4d, 0x99, 0xf6, 0x3e, 0xcc, 0x51, 0x2e, 0xbc, 0x80, 0x47, 0x11, 0x06, 0x49, 0x08, 0x43, 0x2e,
	0x50, 0x52, 0xcd, 0xe5, 0x8a, 0xeb, 0xf8, 0xf6, 0x5c, 0x52, 0x04, 0x9e, 0x44, 0xc5, 0xe7, 0x32,
	0xc0, 0x7c, 0x91, 0xd1, 0x38, 0x7f, 0x58, 0xb0, 0x73, 0x9a, 0x35, 0xac, 0x3f, 0x1f, 0x9d, 0x63,
	0xa0, 0xc9, 0x37, 0x50, 0x62, 0x61, 0xc3, 0x6a, 0x59, 0xfb, 0xdb, 0x9d, 0x47, 0x6e, 0x4a, 0xe7,
	0x4a, 0x11, 0xb8, 0xdd, 0x10, 0x63, 0xcd, 0xc6, 0x0c, 0xe5, 0x51, 0x7d, 0x79, 0xd1, 0x7c, 0x08,
	0x40, 0xaa, 0x0a, 0x25, 0xa3, 0xd1, 0xbe, 0xe5, 0x97, 0x58, 0x48, 0xea, 0x50, 0x9e, 0xe2, 0xa2,
	0x51, 0x6a, 0x59, 0xfb, 0x0f, 0xfc, 0x64, 0x49, 0x08, 0x54, 0x62, 0x3a, 0xc3, 0x46, 0x39, 0xdd,
	0x4a, 0xd7, 0xc4, 0x85, 0x4a, 0x52, 0x93, 0x46, 0xa5, 0x65, 0xed, 0xef, 0x74, 0x6c, 0x37, 0xbd,
	0x1f, 0xee, 0x7a, 0x0c, 0xee, 0x60, 0x21, 0xd0, 0x4f, 0x71, 0xce, 0x13, 0xa8, 0x24, 0x5f, 0xe4,
	0x21, 0xd4, 0x5e, 0xbc, 0x1c, 0x74, 0x7f, 0xea, 0x0e, 0xde, 0xd7, 0xef, 0x91, 0x6d, 0xd8, 0xea,
	0xbf, 0xef, 0xbd, 0x1b, 0x9c, 0xf5, 0xea, 0xd6, 0x61, 0x75, 0x79, 0xd1, 0x2c, 0xd5, 0x2c, 0x67,
	0x59, 0x82, 0x87, 0x86, 0xe8, 0x38, 0xd6, 0x72, 0x71, 0xf7, 0x54, 0xbe, 0x85, 0x9a, 0xc2, 0x8f,
	0x28, 0x99, 0xce, 0xf2, 0xd9, 0xe9, 0xec, 0xad, 0x07, 0x9a, 0xf2, 0xbb, 0x7d, 0x83, 0xf1, 0x73,
	0x74, 0x9a, 0x32, 0xd7, 0xff, 0xa4, 0xcc, 0x35, 0x92, 0xe7, 0x00, 0x81, 0x44, 0xaa, 0x31, 0x1c,
	0x52, 0x9d, 0x26, 0xbe, 0xdd, 0xb1, 0xdd, 0xec, 0x3a, 0xbb, 0xab, 0xfb, 0xee, 0x0e, 0x56, 0xf7,
	0xdd, 0x7f, 0x60, 0xd0, 0x2f, 0x34, 0xf9, 0x12, 0x88, 0xd1, 0xd3, 0x50, 0x65, 0xb5, 0x19, 0xb2,
	0xb0, 0x71, 0xbf, 0x65, 0xed, 0x97, 0xfd, 0xfa, 0xf9, 0x5a, 0xd1, 0xba, 0xa1, 0x73, 0x00, 0xb5,
	0x55, 0x48, 0xa4, 0x06, 0x95, 0xb7, 0x67, 0x6f, 0x8f, 0xeb, 0xf7, 0xc8, 0x16, 0x94, 0xdf, 0x9c,
	0xfd, 0x5c, 0xb7, 0x92, 0x45, 0xaf, 0xfb, 0xaa, 0x5e, 0x4a, 0xce, 0x5e, 0x77, 0x4f, 0x5e, 0xd7,
	0xcb, 0x87, 0xb5, 0xe5, 0x45, 0xb3, 0x52, 0xb3, 0x5a, 0x96, 0x73, 0x0a, 0xcd, 0x97, 0xa9, 0xdb,
	0xcb, 0x19, 0xfa, 0xf8, 0x61, 0x8e, 0x4a, 0x93, 0x36, 0x6c, 0x09, 0xba, 0x88, 0x38, 0x5d, 0x55,
	0xf3, 0xd3, 0x0d, 0xe5, 0xf0, 0x57, 0x18, 0xa7, 0x0b, 0xf6, 0x26, 0x2e, 0x25, 0x78, 0xac, 0x90,
	0x3c, 0x83, 0xaa, 0x44, 0x35, 0x8f, 0xf4, 0x4d, 0x5c, 0x06, 0xe2, 0x7c, 0x07, 0xbb, 0x3e, 0xd2,
	0x70, 0x53, 0x50, 0x4f, 0xff, 0xb5, 0xbb, 0x49, 0x2f, 0x9d, 0x13, 0x68, 0x5c, 0x67, 0xb8, 0x4b,
	0x28, 0xa7, 0xd0, 0xfc, 0x51, 0x84, 0xff, 0x59, 0x85, 0x36, 0x71, 0xdd, 0x25, 0xac, 0x23, 0x68,
	0xbe, 0xc2, 0x08, 0x37, 0x87, 0x75, 0xcb, 0x1a, 0xed, 0x81, 0xbd, 0x89, 0x23, 0x0b, 0xc7, 0xf9,
	0xd3, 0x82, 0xdd, 0x37, 0x4c, 0xe9, 0x4d, 0x0e, 0x3c, 0xa8, 0x8e, 0x59, 0xa4, 0x51, 0x1a, 0x27,
	0xbb, 0xee, 0x6a, 0x1a, 0xb9, 0x54, 0x30, 0xf7, 0xfb, 0xf4, 0x8c, 0xc5, 0x13, 0xdf, 0xc0, 0xc8,
	0x01, 0xd4, 0xb8, 0x0c, 0x51, 0x0e, 0x47, 0x99, 0xb4, 0x92, 0xb8, 0xd6, 0x4c, 0xfa, 0x5c, 0xea,
	0xc4, 0x60, 0x2b, 0x85, 0x1d, 0x2d, 0xc8, 0xd7, 0x89, 0x0b, 0x8c, 0x42, 0x95, 0x8a, 0x6a, 0xbb,
	0xb3, 0x77, 0xd5, 0x05, 0x46, 0x61, 0x1f, 0xcd, 0xa0, 0xf4, 0x0d, 0x96, 0x1c, 0x40, 0x55, 0xd0,
	0x09, 0x8b, 0x27, 0x46, 0x70, 0x8d, 0x75, 0xab, 0x77, 0xc9, 0x19, 0xcd, 0x2c, 0x32, 0x9c, 0xd3,
	0x85, 0xc6, 0xf5, 0x2c, 0x4d, 0x47, 0xda, 0xb0, 0x95, 0x95, 0x5b, 0x35, 0xac, 0x56, 0xb9, 0xb0,
	0xbd, 0x06, 0xe3, 0xfc, 0x65, 0x41, 0xf3, 0x12, 0x97, 0x51, 0xe8, 0xff, 0xb0, 0x66, 0x3d, 0xb0,
	0x37, 0xe5, 0x69, 0xaa, 0xe6, 0x5d, 0xad, 0xda, 0xa3, 0x8d, 0xe3, 0x3e, 0xaf, 0x5b, 0xe7, 0xf7,
	0x72, 0xfe, 0x1c, 0x25, 0x15, 0x65, 0xa8, 0x48, 0x0f, 0xaa, 0xd9, 0x2c, 0x21, 0x2d, 0x63, 0x5c,
	0x38, 0xa6, 0xec, 0x27, 0x37, 0x20, 0x4c, 0x48, 0x27, 0x50, 0x49, 0xa6, 0x01, 0xf9, 0xcc, 0x40,
	0x0b, 0x86, 0x8b, 0xfd, 0xb8, 0xf0, 0xdc, 0x10, 0xf5, 0xa0, 0x9a, 0x29, 0x38, 0x8f, 0xab, 0x70,
	0x38, 0xe4, 0x71, 0xdd, 0x20, 0x79, 0x0a, 0xd5, 0x4c, 0x81, 0x39, 0x5d, 0xa1, 0xa8, 0x73, 0xba,
	0x1b, 0x24, 0x4b, 0x96, 0x17, 0xcd, 0x9d, 0x2b, 0xaf, 0xe1, 0x09, 0x54, 0x92, 0x5e, 0xe5, 0xa9,
	0x17, 0x48, 0x3a, 0x4f, 0xbd, 0x48, 0x0c, 0xb6, 0x79, 0x6f, 0x3b, 0x63, 0xf8, 0x64, 0xbd, 0x91,
	0x8a, 0xfc, 0x60, 0x7c, 0xb4, 0xae, 0x73, 0xac, 0x8b, 0x20, 0x4f, 0xa2, 0xf8, 0xfa, 0xac, 0xfc,
	0x1c, 0x7d, 0xfe, 0xcb, 0xd3, 0x82, 0x5f, 0x9c, 0x23, 0x1a, 0x4c, 0x31, 0x0e, 0x3d, 0x31, 0x9d,
	0x78, 0x62, 0x34, 0xaa, 0xa6, 0x8f, 0xe9, 0x57, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xad,
	0x36, 0xaf, 0xa1, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JournalEntriesClient is the client API for JournalEntries service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JournalEntriesClient interface {
	Create(ctx context.Context, in *CreateJournalEntryRequest, opts ...grpc.CallOption) (*CreateJournalEntryResponse, error)
	Read(ctx context.Context, in *ReadJournalEntryRequest, opts ...grpc.CallOption) (*ReadJournalEntryResponse, error)
	Update(ctx context.Context, in *UpdateJournalEntryRequest, opts ...grpc.CallOption) (*UpdateJournalEntryResponse, error)
	Delete(ctx context.Context, in *DeleteJournalEntryRequest, opts ...grpc.CallOption) (*DeleteJournalEntryResponse, error)
	List(ctx context.Context, in *ListJournalEntryRequest, opts ...grpc.CallOption) (*ListJournalEntryResponse, error)
}

type journalEntriesClient struct {
	cc *grpc.ClientConn
}

func NewJournalEntriesClient(cc *grpc.ClientConn) JournalEntriesClient {
	return &journalEntriesClient{cc}
}

func (c *journalEntriesClient) Create(ctx context.Context, in *CreateJournalEntryRequest, opts ...grpc.CallOption) (*CreateJournalEntryResponse, error) {
	out := new(CreateJournalEntryResponse)
	err := c.cc.Invoke(ctx, "/model.JournalEntries/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalEntriesClient) Read(ctx context.Context, in *ReadJournalEntryRequest, opts ...grpc.CallOption) (*ReadJournalEntryResponse, error) {
	out := new(ReadJournalEntryResponse)
	err := c.cc.Invoke(ctx, "/model.JournalEntries/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalEntriesClient) Update(ctx context.Context, in *UpdateJournalEntryRequest, opts ...grpc.CallOption) (*UpdateJournalEntryResponse, error) {
	out := new(UpdateJournalEntryResponse)
	err := c.cc.Invoke(ctx, "/model.JournalEntries/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalEntriesClient) Delete(ctx context.Context, in *DeleteJournalEntryRequest, opts ...grpc.CallOption) (*DeleteJournalEntryResponse, error) {
	out := new(DeleteJournalEntryResponse)
	err := c.cc.Invoke(ctx, "/model.JournalEntries/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *journalEntriesClient) List(ctx context.Context, in *ListJournalEntryRequest, opts ...grpc.CallOption) (*ListJournalEntryResponse, error) {
	out := new(ListJournalEntryResponse)
	err := c.cc.Invoke(ctx, "/model.JournalEntries/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JournalEntriesServer is the server API for JournalEntries service.
type JournalEntriesServer interface {
	Create(context.Context, *CreateJournalEntryRequest) (*CreateJournalEntryResponse, error)
	Read(context.Context, *ReadJournalEntryRequest) (*ReadJournalEntryResponse, error)
	Update(context.Context, *UpdateJournalEntryRequest) (*UpdateJournalEntryResponse, error)
	Delete(context.Context, *DeleteJournalEntryRequest) (*DeleteJournalEntryResponse, error)
	List(context.Context, *ListJournalEntryRequest) (*ListJournalEntryResponse, error)
}

func RegisterJournalEntriesServer(s *grpc.Server, srv JournalEntriesServer) {
	s.RegisterService(&_JournalEntries_serviceDesc, srv)
}

func _JournalEntries_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalEntriesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalEntries/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalEntriesServer).Create(ctx, req.(*CreateJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalEntries_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalEntriesServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalEntries/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalEntriesServer).Read(ctx, req.(*ReadJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalEntries_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalEntriesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalEntries/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalEntriesServer).Update(ctx, req.(*UpdateJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalEntries_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalEntriesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalEntries/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalEntriesServer).Delete(ctx, req.(*DeleteJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JournalEntries_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJournalEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalEntriesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalEntries/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalEntriesServer).List(ctx, req.(*ListJournalEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JournalEntries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.JournalEntries",
	HandlerType: (*JournalEntriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _JournalEntries_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _JournalEntries_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _JournalEntries_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _JournalEntries_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _JournalEntries_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kodesmil/ks-model/journal.proto",
}

// JournalSubjectsClient is the client API for JournalSubjects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JournalSubjectsClient interface {
	List(ctx context.Context, in *ListJournalSubjectRequest, opts ...grpc.CallOption) (*ListJournalSubjectResponse, error)
}

type journalSubjectsClient struct {
	cc *grpc.ClientConn
}

func NewJournalSubjectsClient(cc *grpc.ClientConn) JournalSubjectsClient {
	return &journalSubjectsClient{cc}
}

func (c *journalSubjectsClient) List(ctx context.Context, in *ListJournalSubjectRequest, opts ...grpc.CallOption) (*ListJournalSubjectResponse, error) {
	out := new(ListJournalSubjectResponse)
	err := c.cc.Invoke(ctx, "/model.JournalSubjects/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JournalSubjectsServer is the server API for JournalSubjects service.
type JournalSubjectsServer interface {
	List(context.Context, *ListJournalSubjectRequest) (*ListJournalSubjectResponse, error)
}

func RegisterJournalSubjectsServer(s *grpc.Server, srv JournalSubjectsServer) {
	s.RegisterService(&_JournalSubjects_serviceDesc, srv)
}

func _JournalSubjects_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJournalSubjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JournalSubjectsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.JournalSubjects/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JournalSubjectsServer).List(ctx, req.(*ListJournalSubjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JournalSubjects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.JournalSubjects",
	HandlerType: (*JournalSubjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _JournalSubjects_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kodesmil/ks-model/journal.proto",
}
