// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kodesmil/ks-model/notification.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationSetting struct {
	Id                    *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EnableNotifications   bool                 `protobuf:"varint,4,opt,name=enable_notifications,json=enableNotifications,proto3" json:"enable_notifications,omitempty"`
	EnableJournalReminder bool                 `protobuf:"varint,5,opt,name=enable_journal_reminder,json=enableJournalReminder,proto3" json:"enable_journal_reminder,omitempty"`
	CronJournalReminder   string               `protobuf:"bytes,6,opt,name=cron_journal_reminder,json=cronJournalReminder,proto3" json:"cron_journal_reminder,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}             `json:"-"`
	XXX_unrecognized      []byte               `json:"-"`
	XXX_sizecache         int32                `json:"-"`
}

func (m *NotificationSetting) Reset()         { *m = NotificationSetting{} }
func (m *NotificationSetting) String() string { return proto.CompactTextString(m) }
func (*NotificationSetting) ProtoMessage()    {}
func (*NotificationSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{0}
}

func (m *NotificationSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationSetting.Unmarshal(m, b)
}
func (m *NotificationSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationSetting.Marshal(b, m, deterministic)
}
func (m *NotificationSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationSetting.Merge(m, src)
}
func (m *NotificationSetting) XXX_Size() int {
	return xxx_messageInfo_NotificationSetting.Size(m)
}
func (m *NotificationSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationSetting.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationSetting proto.InternalMessageInfo

func (m *NotificationSetting) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *NotificationSetting) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *NotificationSetting) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *NotificationSetting) GetEnableNotifications() bool {
	if m != nil {
		return m.EnableNotifications
	}
	return false
}

func (m *NotificationSetting) GetEnableJournalReminder() bool {
	if m != nil {
		return m.EnableJournalReminder
	}
	return false
}

func (m *NotificationSetting) GetCronJournalReminder() string {
	if m != nil {
		return m.CronJournalReminder
	}
	return ""
}

type CreateNotificationSettingRequest struct {
	Payload              *NotificationSetting `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateNotificationSettingRequest) Reset()         { *m = CreateNotificationSettingRequest{} }
func (m *CreateNotificationSettingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationSettingRequest) ProtoMessage()    {}
func (*CreateNotificationSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{1}
}

func (m *CreateNotificationSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationSettingRequest.Unmarshal(m, b)
}
func (m *CreateNotificationSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationSettingRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotificationSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationSettingRequest.Merge(m, src)
}
func (m *CreateNotificationSettingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationSettingRequest.Size(m)
}
func (m *CreateNotificationSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationSettingRequest proto.InternalMessageInfo

func (m *CreateNotificationSettingRequest) GetPayload() *NotificationSetting {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateNotificationSettingResponse struct {
	Result               *NotificationSetting `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateNotificationSettingResponse) Reset()         { *m = CreateNotificationSettingResponse{} }
func (m *CreateNotificationSettingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationSettingResponse) ProtoMessage()    {}
func (*CreateNotificationSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{2}
}

func (m *CreateNotificationSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationSettingResponse.Unmarshal(m, b)
}
func (m *CreateNotificationSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationSettingResponse.Marshal(b, m, deterministic)
}
func (m *CreateNotificationSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationSettingResponse.Merge(m, src)
}
func (m *CreateNotificationSettingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationSettingResponse.Size(m)
}
func (m *CreateNotificationSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationSettingResponse proto.InternalMessageInfo

func (m *CreateNotificationSettingResponse) GetResult() *NotificationSetting {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadNotificationSettingRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadNotificationSettingRequest) Reset()         { *m = ReadNotificationSettingRequest{} }
func (m *ReadNotificationSettingRequest) String() string { return proto.CompactTextString(m) }
func (*ReadNotificationSettingRequest) ProtoMessage()    {}
func (*ReadNotificationSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{3}
}

func (m *ReadNotificationSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNotificationSettingRequest.Unmarshal(m, b)
}
func (m *ReadNotificationSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNotificationSettingRequest.Marshal(b, m, deterministic)
}
func (m *ReadNotificationSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNotificationSettingRequest.Merge(m, src)
}
func (m *ReadNotificationSettingRequest) XXX_Size() int {
	return xxx_messageInfo_ReadNotificationSettingRequest.Size(m)
}
func (m *ReadNotificationSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNotificationSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNotificationSettingRequest proto.InternalMessageInfo

func (m *ReadNotificationSettingRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type ReadNotificationSettingResponse struct {
	Result               *NotificationSetting `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReadNotificationSettingResponse) Reset()         { *m = ReadNotificationSettingResponse{} }
func (m *ReadNotificationSettingResponse) String() string { return proto.CompactTextString(m) }
func (*ReadNotificationSettingResponse) ProtoMessage()    {}
func (*ReadNotificationSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{4}
}

func (m *ReadNotificationSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNotificationSettingResponse.Unmarshal(m, b)
}
func (m *ReadNotificationSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNotificationSettingResponse.Marshal(b, m, deterministic)
}
func (m *ReadNotificationSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNotificationSettingResponse.Merge(m, src)
}
func (m *ReadNotificationSettingResponse) XXX_Size() int {
	return xxx_messageInfo_ReadNotificationSettingResponse.Size(m)
}
func (m *ReadNotificationSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNotificationSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNotificationSettingResponse proto.InternalMessageInfo

func (m *ReadNotificationSettingResponse) GetResult() *NotificationSetting {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateNotificationSettingRequest struct {
	Payload              *NotificationSetting `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateNotificationSettingRequest) Reset()         { *m = UpdateNotificationSettingRequest{} }
func (m *UpdateNotificationSettingRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationSettingRequest) ProtoMessage()    {}
func (*UpdateNotificationSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{5}
}

func (m *UpdateNotificationSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationSettingRequest.Unmarshal(m, b)
}
func (m *UpdateNotificationSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationSettingRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNotificationSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationSettingRequest.Merge(m, src)
}
func (m *UpdateNotificationSettingRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationSettingRequest.Size(m)
}
func (m *UpdateNotificationSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationSettingRequest proto.InternalMessageInfo

func (m *UpdateNotificationSettingRequest) GetPayload() *NotificationSetting {
	if m != nil {
		return m.Payload
	}
	return nil
}

type UpdateNotificationSettingResponse struct {
	Result               *NotificationSetting `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateNotificationSettingResponse) Reset()         { *m = UpdateNotificationSettingResponse{} }
func (m *UpdateNotificationSettingResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNotificationSettingResponse) ProtoMessage()    {}
func (*UpdateNotificationSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{6}
}

func (m *UpdateNotificationSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNotificationSettingResponse.Unmarshal(m, b)
}
func (m *UpdateNotificationSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNotificationSettingResponse.Marshal(b, m, deterministic)
}
func (m *UpdateNotificationSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNotificationSettingResponse.Merge(m, src)
}
func (m *UpdateNotificationSettingResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNotificationSettingResponse.Size(m)
}
func (m *UpdateNotificationSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNotificationSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNotificationSettingResponse proto.InternalMessageInfo

func (m *UpdateNotificationSettingResponse) GetResult() *NotificationSetting {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteNotificationSettingRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteNotificationSettingRequest) Reset()         { *m = DeleteNotificationSettingRequest{} }
func (m *DeleteNotificationSettingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteNotificationSettingRequest) ProtoMessage()    {}
func (*DeleteNotificationSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{7}
}

func (m *DeleteNotificationSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNotificationSettingRequest.Unmarshal(m, b)
}
func (m *DeleteNotificationSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNotificationSettingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteNotificationSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNotificationSettingRequest.Merge(m, src)
}
func (m *DeleteNotificationSettingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteNotificationSettingRequest.Size(m)
}
func (m *DeleteNotificationSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNotificationSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNotificationSettingRequest proto.InternalMessageInfo

func (m *DeleteNotificationSettingRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteNotificationSettingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNotificationSettingResponse) Reset()         { *m = DeleteNotificationSettingResponse{} }
func (m *DeleteNotificationSettingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteNotificationSettingResponse) ProtoMessage()    {}
func (*DeleteNotificationSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{8}
}

func (m *DeleteNotificationSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNotificationSettingResponse.Unmarshal(m, b)
}
func (m *DeleteNotificationSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNotificationSettingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteNotificationSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNotificationSettingResponse.Merge(m, src)
}
func (m *DeleteNotificationSettingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteNotificationSettingResponse.Size(m)
}
func (m *DeleteNotificationSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNotificationSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNotificationSettingResponse proto.InternalMessageInfo

type ListNotificationSettingRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListNotificationSettingRequest) Reset()         { *m = ListNotificationSettingRequest{} }
func (m *ListNotificationSettingRequest) String() string { return proto.CompactTextString(m) }
func (*ListNotificationSettingRequest) ProtoMessage()    {}
func (*ListNotificationSettingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{9}
}

func (m *ListNotificationSettingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNotificationSettingRequest.Unmarshal(m, b)
}
func (m *ListNotificationSettingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNotificationSettingRequest.Marshal(b, m, deterministic)
}
func (m *ListNotificationSettingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNotificationSettingRequest.Merge(m, src)
}
func (m *ListNotificationSettingRequest) XXX_Size() int {
	return xxx_messageInfo_ListNotificationSettingRequest.Size(m)
}
func (m *ListNotificationSettingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNotificationSettingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNotificationSettingRequest proto.InternalMessageInfo

func (m *ListNotificationSettingRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListNotificationSettingRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListNotificationSettingRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListNotificationSettingRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListNotificationSettingResponse struct {
	Results              []*NotificationSetting `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListNotificationSettingResponse) Reset()         { *m = ListNotificationSettingResponse{} }
func (m *ListNotificationSettingResponse) String() string { return proto.CompactTextString(m) }
func (*ListNotificationSettingResponse) ProtoMessage()    {}
func (*ListNotificationSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{10}
}

func (m *ListNotificationSettingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNotificationSettingResponse.Unmarshal(m, b)
}
func (m *ListNotificationSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNotificationSettingResponse.Marshal(b, m, deterministic)
}
func (m *ListNotificationSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNotificationSettingResponse.Merge(m, src)
}
func (m *ListNotificationSettingResponse) XXX_Size() int {
	return xxx_messageInfo_ListNotificationSettingResponse.Size(m)
}
func (m *ListNotificationSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNotificationSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNotificationSettingResponse proto.InternalMessageInfo

func (m *ListNotificationSettingResponse) GetResults() []*NotificationSetting {
	if m != nil {
		return m.Results
	}
	return nil
}

type NotificationDevice struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeviceToken          string               `protobuf:"bytes,4,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NotificationDevice) Reset()         { *m = NotificationDevice{} }
func (m *NotificationDevice) String() string { return proto.CompactTextString(m) }
func (*NotificationDevice) ProtoMessage()    {}
func (*NotificationDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{11}
}

func (m *NotificationDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationDevice.Unmarshal(m, b)
}
func (m *NotificationDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationDevice.Marshal(b, m, deterministic)
}
func (m *NotificationDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationDevice.Merge(m, src)
}
func (m *NotificationDevice) XXX_Size() int {
	return xxx_messageInfo_NotificationDevice.Size(m)
}
func (m *NotificationDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationDevice.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationDevice proto.InternalMessageInfo

func (m *NotificationDevice) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *NotificationDevice) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *NotificationDevice) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *NotificationDevice) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

type CreateNotificationDeviceRequest struct {
	Payload              *NotificationDevice `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateNotificationDeviceRequest) Reset()         { *m = CreateNotificationDeviceRequest{} }
func (m *CreateNotificationDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationDeviceRequest) ProtoMessage()    {}
func (*CreateNotificationDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{12}
}

func (m *CreateNotificationDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationDeviceRequest.Unmarshal(m, b)
}
func (m *CreateNotificationDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNotificationDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationDeviceRequest.Merge(m, src)
}
func (m *CreateNotificationDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationDeviceRequest.Size(m)
}
func (m *CreateNotificationDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationDeviceRequest proto.InternalMessageInfo

func (m *CreateNotificationDeviceRequest) GetPayload() *NotificationDevice {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateNotificationDeviceResponse struct {
	Result               *NotificationDevice `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateNotificationDeviceResponse) Reset()         { *m = CreateNotificationDeviceResponse{} }
func (m *CreateNotificationDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNotificationDeviceResponse) ProtoMessage()    {}
func (*CreateNotificationDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_29867e1975333e4f, []int{13}
}

func (m *CreateNotificationDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNotificationDeviceResponse.Unmarshal(m, b)
}
func (m *CreateNotificationDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNotificationDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateNotificationDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNotificationDeviceResponse.Merge(m, src)
}
func (m *CreateNotificationDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNotificationDeviceResponse.Size(m)
}
func (m *CreateNotificationDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNotificationDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNotificationDeviceResponse proto.InternalMessageInfo

func (m *CreateNotificationDeviceResponse) GetResult() *NotificationDevice {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*NotificationSetting)(nil), "model.NotificationSetting")
	proto.RegisterType((*CreateNotificationSettingRequest)(nil), "model.CreateNotificationSettingRequest")
	proto.RegisterType((*CreateNotificationSettingResponse)(nil), "model.CreateNotificationSettingResponse")
	proto.RegisterType((*ReadNotificationSettingRequest)(nil), "model.ReadNotificationSettingRequest")
	proto.RegisterType((*ReadNotificationSettingResponse)(nil), "model.ReadNotificationSettingResponse")
	proto.RegisterType((*UpdateNotificationSettingRequest)(nil), "model.UpdateNotificationSettingRequest")
	proto.RegisterType((*UpdateNotificationSettingResponse)(nil), "model.UpdateNotificationSettingResponse")
	proto.RegisterType((*DeleteNotificationSettingRequest)(nil), "model.DeleteNotificationSettingRequest")
	proto.RegisterType((*DeleteNotificationSettingResponse)(nil), "model.DeleteNotificationSettingResponse")
	proto.RegisterType((*ListNotificationSettingRequest)(nil), "model.ListNotificationSettingRequest")
	proto.RegisterType((*ListNotificationSettingResponse)(nil), "model.ListNotificationSettingResponse")
	proto.RegisterType((*NotificationDevice)(nil), "model.NotificationDevice")
	proto.RegisterType((*CreateNotificationDeviceRequest)(nil), "model.CreateNotificationDeviceRequest")
	proto.RegisterType((*CreateNotificationDeviceResponse)(nil), "model.CreateNotificationDeviceResponse")
}

func init() {
	proto.RegisterFile("github.com/kodesmil/ks-model/notification.proto", fileDescriptor_29867e1975333e4f)
}

var fileDescriptor_29867e1975333e4f = []byte{
	// 910 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xed, 0x6e, 0x1a, 0x47,
	0x14, 0xd5, 0x62, 0x67, 0x63, 0x5f, 0x5b, 0x55, 0x35, 0x0e, 0x0a, 0xa0, 0x28, 0x26, 0x54, 0x8e,
	0x91, 0x22, 0x76, 0x1d, 0x62, 0xb5, 0x72, 0x7e, 0x35, 0x6e, 0xda, 0x2a, 0x51, 0x55, 0x55, 0x38,
	0x34, 0x69, 0xf3, 0x03, 0x0d, 0xbb, 0x17, 0x3a, 0x65, 0xd8, 0xd9, 0xcc, 0x0c, 0x56, 0x78, 0x34,
	0x78, 0xa5, 0xaa, 0x6f, 0x50, 0x55, 0xd5, 0xce, 0x0c, 0x14, 0x30, 0xb0, 0x96, 0xa2, 0xaa, 0x7f,
	0x6c, 0xec, 0x7b, 0xce, 0xb9, 0x77, 0xee, 0xc7, 0x11, 0x10, 0xf6, 0x99, 0xfe, 0x6d, 0xd4, 0x0d,
	0x22, 0x31, 0x0c, 0x07, 0x22, 0x46, 0x35, 0x64, 0x3c, 0x1c, 0xa8, 0xc6, 0x50, 0xc4, 0xc8, 0xc3,
	0x44, 0x68, 0xd6, 0x63, 0x11, 0xd5, 0x4c, 0x24, 0x41, 0x2a, 0x85, 0x16, 0xe4, 0x8e, 0x89, 0x54,
	0xaa, 0x7d, 0x21, 0xfa, 0x1c, 0x43, 0xf3, 0xcf, 0xee, 0xa8, 0x17, 0xf6, 0x18, 0xf2, 0xb8, 0x33,
	0xa4, 0x6a, 0x60, 0x81, 0x95, 0xe3, 0x55, 0x84, 0x66, 0x43, 0x54, 0x9a, 0x0e, 0x53, 0x07, 0x78,
	0xe0, 0x00, 0x34, 0x65, 0x21, 0x4d, 0x12, 0xa1, 0x4d, 0x1a, 0xe5, 0xa2, 0x4f, 0xcc, 0xaf, 0xa8,
	0xd1, 0xc7, 0xa4, 0x71, 0x4d, 0x39, 0x8b, 0xa9, 0xc6, 0xf0, 0xc6, 0x07, 0x07, 0x7e, 0xbe, 0xf0,
	0x0a, 0x96, 0xf4, 0x44, 0x97, 0x8b, 0x8f, 0x22, 0xc5, 0x24, 0x5c, 0x10, 0xe9, 0x0b, 0x39, 0x0c,
	0x45, 0x6a, 0x72, 0x84, 0xd9, 0x1f, 0x8e, 0x7b, 0x71, 0x5b, 0xae, 0x1e, 0xa7, 0xa8, 0xec, 0x4f,
	0x47, 0x7d, 0xbd, 0x89, 0x4a, 0x35, 0xa7, 0xaa, 0x41, 0xd3, 0xb4, 0xa1, 0x85, 0xe0, 0x03, 0xa6,
	0xc3, 0x0f, 0x23, 0x94, 0xe3, 0x30, 0x12, 0x9c, 0x63, 0x94, 0x95, 0xd0, 0x11, 0x29, 0x4a, 0xaa,
	0x85, 0x9c, 0x69, 0x7d, 0x7b, 0x7b, 0x2d, 0x99, 0x46, 0xa1, 0x44, 0x25, 0x46, 0x32, 0xc2, 0xf9,
	0x07, 0x2b, 0x53, 0xfb, 0xb3, 0x00, 0x47, 0x3f, 0x2e, 0x4c, 0xed, 0x0a, 0xb5, 0x66, 0x49, 0x9f,
	0x7c, 0x05, 0x05, 0x16, 0x97, 0xbc, 0xaa, 0x57, 0x3f, 0x68, 0x16, 0x03, 0xa3, 0x19, 0xc8, 0x34,
	0x0a, 0x5e, 0xc5, 0x98, 0x64, 0x68, 0x94, 0x97, 0x9f, 0x4f, 0x27, 0xe5, 0x43, 0x00, 0xe2, 0x2b,
	0x94, 0x8c, 0xf2, 0xba, 0xd7, 0x2a, 0xb0, 0x98, 0x5c, 0x00, 0x44, 0x12, 0xa9, 0xc6, 0xb8, 0x43,
	0x75, 0xa9, 0x60, 0x04, 0x2a, 0x81, 0x1d, 0x5d, 0x30, 0x9b, 0x6d, 0xf0, 0x66, 0x36, 0xdb, 0xd6,
	0xbe, 0x43, 0xbf, 0xd0, 0x19, 0x75, 0x94, 0xc6, 0x33, 0xea, 0x4e, 0x3e, 0xd5, 0xa1, 0x5f, 0x68,
	0xf2, 0x14, 0xee, 0x61, 0x42, 0xbb, 0x1c, 0x3b, 0x8b, 0x2b, 0xa8, 0x4a, 0xbb, 0x55, 0xaf, 0xbe,
	0xd7, 0x3a, 0xb2, 0xb1, 0xc5, 0x77, 0x2a, 0xf2, 0x25, 0xdc, 0x77, 0x94, 0xdf, 0xc5, 0x48, 0x26,
	0x94, 0x77, 0x24, 0x0e, 0x59, 0x12, 0xa3, 0x2c, 0xdd, 0x31, 0xac, 0xa2, 0x0d, 0xbf, 0xb6, 0xd1,
	0x96, 0x0b, 0x92, 0x26, 0x14, 0x23, 0x29, 0x92, 0x9b, 0x2c, 0xbf, 0xea, 0xd5, 0xf7, 0x5b, 0x47,
	0x59, 0x70, 0x85, 0xf3, 0x7c, 0x6f, 0x3a, 0x29, 0xef, 0xee, 0x79, 0x55, 0xaf, 0xf6, 0x0e, 0xaa,
	0xdf, 0x98, 0x07, 0xaf, 0x69, 0x7a, 0x0b, 0x3f, 0x8c, 0x50, 0x69, 0x72, 0x0e, 0x77, 0x53, 0x3a,
	0xe6, 0x82, 0xce, 0x06, 0x50, 0x09, 0xcc, 0x11, 0x05, 0xeb, 0x38, 0x33, 0x68, 0xed, 0x2d, 0x3c,
	0xda, 0xa2, 0xac, 0x52, 0x91, 0x28, 0x24, 0x4d, 0xf0, 0x25, 0xaa, 0x11, 0xd7, 0xb7, 0x50, 0x76,
	0xc8, 0xda, 0xf7, 0xf0, 0xb0, 0x85, 0x34, 0xde, 0x52, 0xf0, 0x49, 0xee, 0xb2, 0x64, 0xab, 0x51,
	0x6b, 0xc3, 0xf1, 0x46, 0xa1, 0x4f, 0xa8, 0xef, 0x1d, 0x54, 0xdb, 0x66, 0x11, 0xfe, 0x8b, 0x96,
	0x6e, 0x51, 0xfe, 0x84, 0x92, 0x5f, 0x41, 0xf5, 0x25, 0x72, 0xdc, 0x5a, 0xf2, 0x2d, 0x9b, 0xfa,
	0x05, 0x3c, 0xda, 0x22, 0x65, 0x6b, 0xac, 0xfd, 0xe1, 0xc1, 0xc3, 0x1f, 0x98, 0xd2, 0x5b, 0xd2,
	0x85, 0xe0, 0xf7, 0x18, 0xd7, 0x28, 0x5d, 0xca, 0xfb, 0xc1, 0xcc, 0x55, 0x02, 0x9a, 0xb2, 0xe0,
	0x3b, 0x13, 0x33, 0x6f, 0xb0, 0x30, 0x72, 0x06, 0x7b, 0x42, 0xc6, 0x28, 0x3b, 0xdd, 0xb1, 0x3b,
	0xf3, 0xe2, 0x32, 0xe5, 0x4a, 0x48, 0xdb, 0x4e, 0x03, 0xbb, 0x1c, 0x93, 0xf3, 0x2c, 0x05, 0xf2,
	0x58, 0xb9, 0xdb, 0x7e, 0xb0, 0x9a, 0x02, 0x79, 0x7c, 0x85, 0xce, 0xf0, 0x5a, 0x0e, 0x4b, 0xce,
	0xc0, 0x4f, 0x69, 0x9f, 0x25, 0x7d, 0x73, 0xcc, 0x07, 0xcd, 0xd2, 0x32, 0xeb, 0xa7, 0x2c, 0x46,
	0x2d, 0xc3, 0xe2, 0x6a, 0x6f, 0xe1, 0x78, 0xe3, 0x63, 0xdd, 0xd0, 0xce, 0xe1, 0xae, 0x1d, 0x85,
	0x2a, 0x79, 0xd5, 0x9d, 0xbc, 0x7d, 0x70, 0xd0, 0xda, 0x5f, 0x1e, 0x90, 0x45, 0xc0, 0x4b, 0xbc,
	0x66, 0x11, 0x92, 0x8b, 0x7c, 0xaf, 0x24, 0xd3, 0x49, 0xf9, 0x33, 0x38, 0xfc, 0xd7, 0x2b, 0xbf,
	0xfe, 0x3f, 0xdd, 0xf2, 0x09, 0x1c, 0xc6, 0xa6, 0xf4, 0x8e, 0x16, 0x03, 0x4c, 0x4c, 0x63, 0xf7,
	0x2f, 0x8d, 0x49, 0x41, 0xe1, 0xcc, 0x6b, 0x1d, 0xd8, 0xe8, 0x9b, 0x2c, 0xb8, 0xe0, 0x5d, 0x3f,
	0xc3, 0xf1, 0x4d, 0x87, 0xb1, 0x3d, 0x98, 0x6d, 0xd1, 0xb3, 0xd5, 0x3b, 0x2b, 0xaf, 0xe9, 0xab,
	0xa3, 0xcc, 0xcf, 0xac, 0xbd, 0xce, 0x13, 0x67, 0xba, 0x6e, 0x60, 0x4f, 0x57, 0xae, 0x6c, 0x8b,
	0xae, 0x03, 0x36, 0xff, 0xde, 0x81, 0x7b, 0x6b, 0xc6, 0xa9, 0xc8, 0x7b, 0xf0, 0x6d, 0x3e, 0x72,
	0xea, 0x54, 0xf2, 0x2c, 0xb9, 0x52, 0xcf, 0x07, 0xba, 0x42, 0xdb, 0xb0, 0x9b, 0x99, 0x1c, 0x39,
	0x71, 0x8c, 0xed, 0xd6, 0x59, 0x79, 0x9c, 0x07, 0x73, 0xb2, 0xef, 0xc1, 0xb7, 0x56, 0x34, 0xaf,
	0x39, 0xcf, 0xf3, 0xe6, 0x35, 0xe7, 0x5b, 0xd8, 0x35, 0xf8, 0xd6, 0x43, 0xe6, 0xe2, 0x79, 0xee,
	0x34, 0x17, 0xcf, 0xf7, 0x9e, 0xf2, 0x74, 0x52, 0x2e, 0xae, 0xff, 0x92, 0xd1, 0x86, 0xdd, 0xec,
	0x50, 0xe7, 0xbd, 0xda, 0x6e, 0x51, 0xf3, 0x5e, 0xe5, 0x1c, 0x77, 0xc5, 0x9f, 0x4e, 0xca, 0x85,
	0x3d, 0xaf, 0xf9, 0x71, 0x39, 0xab, 0x5d, 0x0f, 0x45, 0x7e, 0x99, 0x8f, 0xff, 0xf1, 0xc6, 0xa9,
	0x2e, 0x6d, 0x75, 0xe5, 0x34, 0x17, 0xb7, 0x9c, 0xf9, 0xf2, 0xf4, 0xd7, 0x93, 0x0d, 0xdf, 0x93,
	0xbb, 0x34, 0x1a, 0x60, 0x12, 0x87, 0xe9, 0xa0, 0x1f, 0xa6, 0xdd, 0xae, 0x6f, 0x0e, 0xf5, 0xd9,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x61, 0x20, 0x55, 0x57, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotificationSettingsClient is the client API for NotificationSettings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationSettingsClient interface {
	Create(ctx context.Context, in *CreateNotificationSettingRequest, opts ...grpc.CallOption) (*CreateNotificationSettingResponse, error)
	Read(ctx context.Context, in *ReadNotificationSettingRequest, opts ...grpc.CallOption) (*ReadNotificationSettingResponse, error)
	Update(ctx context.Context, in *UpdateNotificationSettingRequest, opts ...grpc.CallOption) (*UpdateNotificationSettingResponse, error)
	Delete(ctx context.Context, in *DeleteNotificationSettingRequest, opts ...grpc.CallOption) (*DeleteNotificationSettingResponse, error)
	List(ctx context.Context, in *ListNotificationSettingRequest, opts ...grpc.CallOption) (*ListNotificationSettingResponse, error)
}

type notificationSettingsClient struct {
	cc *grpc.ClientConn
}

func NewNotificationSettingsClient(cc *grpc.ClientConn) NotificationSettingsClient {
	return &notificationSettingsClient{cc}
}

func (c *notificationSettingsClient) Create(ctx context.Context, in *CreateNotificationSettingRequest, opts ...grpc.CallOption) (*CreateNotificationSettingResponse, error) {
	out := new(CreateNotificationSettingResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationSettings/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationSettingsClient) Read(ctx context.Context, in *ReadNotificationSettingRequest, opts ...grpc.CallOption) (*ReadNotificationSettingResponse, error) {
	out := new(ReadNotificationSettingResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationSettings/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationSettingsClient) Update(ctx context.Context, in *UpdateNotificationSettingRequest, opts ...grpc.CallOption) (*UpdateNotificationSettingResponse, error) {
	out := new(UpdateNotificationSettingResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationSettings/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationSettingsClient) Delete(ctx context.Context, in *DeleteNotificationSettingRequest, opts ...grpc.CallOption) (*DeleteNotificationSettingResponse, error) {
	out := new(DeleteNotificationSettingResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationSettings/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationSettingsClient) List(ctx context.Context, in *ListNotificationSettingRequest, opts ...grpc.CallOption) (*ListNotificationSettingResponse, error) {
	out := new(ListNotificationSettingResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationSettings/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationSettingsServer is the server API for NotificationSettings service.
type NotificationSettingsServer interface {
	Create(context.Context, *CreateNotificationSettingRequest) (*CreateNotificationSettingResponse, error)
	Read(context.Context, *ReadNotificationSettingRequest) (*ReadNotificationSettingResponse, error)
	Update(context.Context, *UpdateNotificationSettingRequest) (*UpdateNotificationSettingResponse, error)
	Delete(context.Context, *DeleteNotificationSettingRequest) (*DeleteNotificationSettingResponse, error)
	List(context.Context, *ListNotificationSettingRequest) (*ListNotificationSettingResponse, error)
}

func RegisterNotificationSettingsServer(s *grpc.Server, srv NotificationSettingsServer) {
	s.RegisterService(&_NotificationSettings_serviceDesc, srv)
}

func _NotificationSettings_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationSettingsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationSettings/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationSettingsServer).Create(ctx, req.(*CreateNotificationSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationSettings_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNotificationSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationSettingsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationSettings/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationSettingsServer).Read(ctx, req.(*ReadNotificationSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationSettings_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNotificationSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationSettingsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationSettings/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationSettingsServer).Update(ctx, req.(*UpdateNotificationSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationSettings_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNotificationSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationSettingsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationSettings/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationSettingsServer).Delete(ctx, req.(*DeleteNotificationSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationSettings_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationSettingsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationSettings/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationSettingsServer).List(ctx, req.(*ListNotificationSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationSettings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.NotificationSettings",
	HandlerType: (*NotificationSettingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NotificationSettings_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _NotificationSettings_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NotificationSettings_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _NotificationSettings_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NotificationSettings_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kodesmil/ks-model/notification.proto",
}

// NotificationDevicesClient is the client API for NotificationDevices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationDevicesClient interface {
	Create(ctx context.Context, in *CreateNotificationDeviceRequest, opts ...grpc.CallOption) (*CreateNotificationDeviceResponse, error)
}

type notificationDevicesClient struct {
	cc *grpc.ClientConn
}

func NewNotificationDevicesClient(cc *grpc.ClientConn) NotificationDevicesClient {
	return &notificationDevicesClient{cc}
}

func (c *notificationDevicesClient) Create(ctx context.Context, in *CreateNotificationDeviceRequest, opts ...grpc.CallOption) (*CreateNotificationDeviceResponse, error) {
	out := new(CreateNotificationDeviceResponse)
	err := c.cc.Invoke(ctx, "/model.NotificationDevices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationDevicesServer is the server API for NotificationDevices service.
type NotificationDevicesServer interface {
	Create(context.Context, *CreateNotificationDeviceRequest) (*CreateNotificationDeviceResponse, error)
}

func RegisterNotificationDevicesServer(s *grpc.Server, srv NotificationDevicesServer) {
	s.RegisterService(&_NotificationDevices_serviceDesc, srv)
}

func _NotificationDevices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationDevicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NotificationDevices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationDevicesServer).Create(ctx, req.(*CreateNotificationDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationDevices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.NotificationDevices",
	HandlerType: (*NotificationDevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NotificationDevices_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/kodesmil/ks-model/notification.proto",
}
